# Evaluate the Badini CosyVoice3 model on the whole test set
Run with the **cosyvoice** kernel, after training (needs `model_ft` from section 12 of the training notebook).
Synthesizes **every** test sentence, then scores: SIM-o (prompt + real sentence), UTMOS, RTF, duration ratio, optional CER/WER.
Resumable: existing wavs are not re-synthesized.

In [1]:
import sys, subprocess, importlib.util, os
print("python:", sys.executable)          # want /workspace/envs/cosyvoice/bin/python
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "0"
need = {"soundfile": "soundfile", "pandas": "pandas", "speechbrain": "speechbrain"}
missing = [pip for mod, pip in need.items() if importlib.util.find_spec(mod) is None]
print("missing:", missing or "nothing")
if missing:
    r = subprocess.run([sys.executable, "-m", "pip", "install", "--no-input", "--default-timeout", "30", *missing],
                       text=True, timeout=600)
    print("pip exit code:", r.returncode)
print("deps OK")

python: /workspace/envs/cosyvoice/bin/python
missing: nothing
deps OK

In [ ]:
import sys, subprocess, os
print('python:', sys.executable)
os.environ['HF_HUB_ENABLE_HF_TRANSFER'] = '0'
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'soundfile', 'pandas', 'speechbrain'], check=True)

In [2]:
import os, re, sys, csv, json, time, collections
import torch, torchaudio, numpy as np, soundfile as sf

# ---- paths (same as training notebook cell 1)
DATA_ROOT = "/workspace/Data24_09_2026"
AUDIO_DIR = f"{DATA_ROOT}/clips"
TRAIN_TSV = f"{DATA_ROOT}/train_all.tsv"
TEST_TSV  = f"{DATA_ROOT}/test_all.tsv"      # the test set
SPK_COL, PATH_COL, TEXT_COL, HAS_HEADER = 0, 1, 3, True
WORK      = "/workspace/cosyvoice3_badini_all"
COSY_REPO = "/workspace/CosyVoice"
MODEL_DIR = f"{WORK}/model_ft"
INSTRUCT  = "You are a helpful assistant.<|endofprompt|>"

LIMIT     = 0        # max sentences per speaker; 0 = ALL.  Use e.g. 20 for a quick check
ASR_MODEL = ""       # optional HF id of an ASR model that handles Badini -> adds CER/WER
ASR_LANG  = ""
OUT_DIR   = f"{WORK}/eval_test_all"
SYNTH_DIR = f"{OUT_DIR}/wavs"
os.makedirs(SYNTH_DIR, exist_ok=True)
sys.path.append(f"{COSY_REPO}/third_party/Matcha-TTS"); sys.path.append(COSY_REPO)
dev = "cuda" if torch.cuda.is_available() else "cpu"

## 1 · Badini number → words converter (same as training notebook)

In [3]:
# ---- digits -> Badini words (spelling from your corrected Excel sheet; EDIT here if a word is wrong) ----
ONES  = {1:"ئێک",2:"دو",3:"سێ",4:"چار",5:"پێنج",6:"شەش",7:"حەفت",8:"هەشت",9:"نەه",
         10:"دەه",11:"یازدە",12:"دوازدە",13:"سیزدە",14:"چاردە",15:"پازدە",
         16:"شازدە",17:"حەڤدە",18:"هەژدە",19:"نوزدە"}
TENS  = {2:"بیست",3:"سیه",4:"چل",5:"پێنجی",6:"شێست",7:"حەفتێ",8:"هەشتا",9:"نوت"}
HUND, THOU, ZERO, AND = "سەد", "هزار", "سفر", " و "
POINT, HOUR, MINUTE, SECOND = "پوینت", "دەمژمێر", "خولەک", "چرکە"   # HOUR is said BEFORE the hour number
PLUS, MINUS = "کومکرنی", "ژێبرن"
DAY, MONTH, YEAR = "رۆژا", "هەیڤا", "سالا"
CURR = {"$": ("دولار", "سەنت"), "€": ("یۆرۆ", "سەنت")}   # symbol -> (main unit, cents)
D = "0-9٠-٩۰-۹"

def _below100(r):
    if r < 20: return ONES[r]
    t, u = divmod(r, 10)
    return TENS[t] + (AND + ONES[u] if u else "")

def _below1000(n):
    h, r = divmod(n, 100)
    parts = []
    if h: parts.append(HUND if h == 1 else ONES[h] + " " + HUND)
    if r: parts.append(_below100(r))
    return AND.join(parts)

def num2words_badini(n):
    if n == 0: return ZERO
    th, r = divmod(n, 1000)
    parts = []
    if th: parts.append(THOU if th == 1 else _below1000(th) + " " + THOU)
    if r:  parts.append(_below1000(r))
    return AND.join(parts)

_ASCII = str.maketrans("٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹", "01234567890123456789")

def _int(s):                       # digit string -> words (0-999999; longer numbers / 007 codes stay as digits)
    s = s.translate(_ASCII)
    if len(s) > 1 and s[0] == "0": return s
    n = int(s)
    return num2words_badini(n) if n <= 999999 else s

def _frac(s):                      # fraction read as a number:  23 -> بیست و سێ ;  05 -> سفر پێنج
    s = s.translate(_ASCII); z = len(s) - len(s.lstrip("0")); rest = s.lstrip("0")
    return " ".join([ZERO] * z + ([_int(rest)] if rest else []))

def _num(s):                       # 34.567 / 45.6 / 12
    s = s.translate(_ASCII)
    if "." in s:
        i, f = s.split(".", 1)
        return f"{_int(i)} {POINT} {_frac(f)}"
    return _int(s)

def _money(s, sym):                # 45.6$ -> چل و پێنج دولار و شەش سەنت
    main, cent = CURR[sym]; s = s.translate(_ASCII)
    i, _, f = s.partition(".")
    out = f"{_int(i)} {main}"
    if f.strip("0"): out += f"{AND}{_int(f.lstrip('0'))} {cent}"
    return out

def _time(m):                      # 21:45:30 -> دەمژمێر بیست و ئێک و چل و پێنج خولەک و سیه چرکە
    h, mi, se = m.group(1), m.group(2), m.group(3)
    out = [f"{HOUR} {_int(h)}"]
    if int(mi.translate(_ASCII)): out.append(f"{_int(mi)} {MINUTE}")
    if se and int(se.translate(_ASCII)): out.append(f"{_int(se)} {SECOND}")
    return AND.join(out)

def _date(m):
    g = m.groups()
    if len(g[0].translate(_ASCII)) == 4: y, mo, d = g[0], g[1], g[2]     # 2026/11/23
    else:                                d, mo, y = g[0], g[1], g[2]     # 23/11/2026
    before = m.string[:m.start()].rstrip()
    day = "" if re.search(r"[ڕر]ۆژا$", before) else DAY + " "     # text already says "ڕۆژا" -> don't repeat it
    return f"{day}{_int(d)}، {MONTH} {_int(mo)}، {YEAR} {_int(y)}"

def digits_to_words(text):
    # 0) Arabic decimal/thousands marks -> ASCII; minus; plus
    text = text.replace("٫", ".").replace("٬", ",")
    text = re.sub(rf"(?<!\w)[-−](?=[{D}])", f"{MINUS} ", text)          # -234 / -56.23 (not 2020-2024)
    text = re.sub(rf"(?<=[{D}])\s*\+\s*(?=[{D}])", f" {PLUS} ", text)       # 234+ 78
    # 1) dates  2026/11/23, 23/11/2026 or 10\7\2018 (backslash form used in your data)
    text = re.sub(rf"(?<![{D}])([{D}]{{4}}|[{D}]{{1,2}})[/\\]([{D}]{{1,2}})[/\\]([{D}]{{4}}|[{D}]{{1,2}})(?![{D}])", _date, text)
    # 2) time  21:45:30 / 21:45
    text = re.sub(rf"(?<![{D}])([{D}]{{1,2}}):([{D}]{{2}})(?::([{D}]{{2}}))?(?![{D}])", _time, text)
    # 3) thousands commas  1,250 -> 1250
    text = re.sub(rf"(?<=[{D}]),(?=[{D}]{{3}}(?![{D}]))", "", text)
    # 4) currency  45.6$  /  $45.6
    sym = "".join(re.escape(k) for k in CURR)
    text = re.sub(rf"([{D}]+(?:\.[{D}]+)?)\s*([{sym}])", lambda m: _money(m.group(1), m.group(2)), text)
    text = re.sub(rf"([{sym}])\s*([{D}]+(?:\.[{D}]+)?)", lambda m: _money(m.group(2), m.group(1)), text)
    # 5) decimals and plain numbers
    return re.sub(rf"[{D}]+(?:\.[{D}]+)?", lambda m: _num(m.group(0)), text)

## 2 · Helpers

In [4]:
def read_tsv(tsv, audio_dir):
    rows, miss, empty = [], 0, 0
    with open(tsv, encoding="utf-8-sig") as f:
        lines = f.readlines()
    if HAS_HEADER: lines = lines[1:]
    for l in lines:
        l = l.rstrip("\n")
        if not l.strip(): continue
        p = l.split("\t")
        if len(p) <= max(SPK_COL, PATH_COL, TEXT_COL): continue
        spk, fn, text = p[SPK_COL].strip(), p[PATH_COL].strip(), p[TEXT_COL].strip()
        if not text: empty += 1; continue
        wav = f"{audio_dir}/{fn}"
        if not os.path.exists(wav): miss += 1; continue
        rows.append((spk, fn, text, wav))
    print(f"  {os.path.basename(tsv)}: {len(rows)} usable | {miss} missing-audio | {empty} empty-text")
    return rows

def uid(fn): return os.path.splitext(os.path.basename(fn))[0]

def edit_distance(a, b):
    prev = list(range(len(b) + 1))
    for i, x in enumerate(a, 1):
        cur = [i]
        for j, y in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j-1] + 1, prev[j-1] + (x != y)))
        prev = cur
    return prev[-1]

_PUNCT = re.compile(r"[\u060c\u061b\u061f\u066b\u066c.,;:!?\"'()\[\]{}\-\u2013\u2014\u2026]")
def norm_text(t):
    t = _PUNCT.sub(" ", t).replace("\u064a", "\u06cc").replace("\u0643", "\u06a9")
    return re.sub(r"\s+", " ", t).strip()

## 3 · Load the test set + a clean prompt per speaker (from TRAIN data, never a test clip)

In [5]:
train_rows = read_tsv(TRAIN_TSV, AUDIO_DIR)
test_rows  = read_tsv(TEST_TSV,  AUDIO_DIR)
claims = collections.defaultdict(set)
for spk, fn, _, _ in train_rows + test_rows: claims[fn].add(spk)
bad = {fn for fn, s in claims.items() if len(s) > 1}
test = {uid(fn): (wav, text, spk) for spk, fn, text, wav in test_rows if fn not in bad}
train = {uid(fn): (wav, text, spk) for spk, fn, text, wav in train_rows if fn not in bad and uid(fn) not in test}
SPEAKERS = sorted({v[2] for v in train.values()})
per_spk = collections.defaultdict(list)
for u in sorted(test):
    if test[u][2] in SPEAKERS: per_spk[test[u][2]].append(u)
if LIMIT: per_spk = {s: ids[:LIMIT] for s, ids in per_spk.items()}
print("test sentences per speaker:", {s: len(i) for s, i in per_spk.items()})

PROMPT = {}
for s in SPEAKERS:
    for u in sorted(train):
        w, t, sp = train[u]
        if sp != s: continue
        try:
            if 3.0 <= sf.info(w).duration <= 12.0: PROMPT[s] = (w, t); break
        except Exception: continue
assert set(PROMPT) == set(SPEAKERS), "no 3-12 s prompt clip found for some speaker"
print("prompts:", {s: os.path.basename(p[0]) for s, p in PROMPT.items()})

  train_all.tsv: 10945 usable | 0 missing-audio | 0 empty-text
  test_all.tsv: 303 usable | 0 missing-audio | 0 empty-text
test sentences per speaker: {'bafreen': 101, 'abdullah': 101, 'hayfa': 101}
prompts: {'abdullah': '2_44100_a1.wav', 'bafreen': '1_44100_a100.wav', 'hayfa': 'hayfa98_44100_a1.wav'}

## 4 · Synthesize ALL test sentences (resumable, timed)

In [6]:
from cosyvoice.cli.cosyvoice import AutoModel
cosy = AutoModel(model_dir=MODEL_DIR); sr = cosy.sample_rate
timing_path = f"{OUT_DIR}/timing.json"
timing = json.load(open(timing_path)) if os.path.exists(timing_path) else {}
for s, ids in per_spk.items():
    os.makedirs(f"{SYNTH_DIR}/{s}", exist_ok=True); pw, pt = PROMPT[s]
    for k, u in enumerate(ids, 1):
        out = f"{SYNTH_DIR}/{s}/{u}.wav"
        if os.path.exists(out): continue
        text = digits_to_words(test[u][1])
        try:
            if dev == "cuda": torch.cuda.synchronize()
            t0 = time.time()
            chunks = [j["tts_speech"] for j in cosy.inference_zero_shot(
                text, INSTRUCT + pt, pw, stream=False, text_frontend=False)]
            if dev == "cuda": torch.cuda.synchronize()
            el = time.time() - t0
            wav = chunks[0] if len(chunks) == 1 else torch.cat(chunks, dim=1)
            torchaudio.save(out, wav, sr)
            timing[f"{s}/{u}"] = dict(sec=el, audio_sec=wav.shape[1] / sr)
        except Exception as e:
            print(f"  !! synth failed {s}/{u}: {e}")
        if k % 25 == 0 or k == len(ids):
            print(f"  {s}: {k}/{len(ids)}"); json.dump(timing, open(timing_path, "w"))
json.dump(timing, open(timing_path, "w"))
del cosy
if dev == "cuda": torch.cuda.empty_cache()

/workspace/envs/cosyvoice/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[2026-10-13 08:34:26,473] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)

/workspace/envs/cosyvoice/bin/x86_64-conda-linux-gnu-ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/workspace/envs/cosyvoice/bin/x86_64-conda-linux-gnu-ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.
/workspace/envs/cosyvoice/lib/python3.10/site-packages/lightning/fabric/__init__.py:41: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
2026-10-13 08:35:32,045 INFO input frame rate=25
/workspace/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
2026-10-13 08:35:38.933356029 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory

2026-10-13 08:35:38.933381579 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:870 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
2026-10-13 08:35:40,739 DEBUG Starting new HTTPS connection (1): www.modelscope.cn:443

Downloading Model to directory: /root/.cache/modelscope/hub/pengzhendong/wetext

2026-10-13 08:35:42,943 DEBUG https://www.modelscope.cn:443 "GET /api/v1/models/pengzhendong/wetext/revisions HTTP/1.1" 403 137
2026-10-13 08:35:42,944 - modelscope - ERROR - Authentication token does not exist,
2026-10-13 08:35:42,945 INFO no frontend is avaliable
  0%|          | 0/1 [00:00<?, ?it/s]/workspace/envs/cosyvoice/lib/python3.10/site-packages/torchaudio/_backend/utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
2026-10-13 08:35:55,268 INFO synthesis text لەوما خو ئێخستە سەر پشتا خو و بەرێ خو دا تایێت مشمشێ و دەڤێ خو ڤەکر، کا چ ناکەڤنە د دەڤێ وی دا.
/workspace/CosyVoice/cosyvoice/cli/model.py:103: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with self.llm_context, torch.cuda.amp.autocast(self.fp16 is True and hasattr(self.llm, 'vllm') is False):
/workspace/CosyVoice/cosyvoice/cli/model.py:426: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self.fp16):
2026-10-13 08:36:05,313 INFO yield speech len 8.04, rtf 1.2492659969709408
100%|██████████| 1/1 [00:11<00:00, 11.55s/it]
/workspace/envs/cosyvoice/lib/python3.10/site-packages/torchaudio/_backend/utils.py:337: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.save_with_torchcodec` under the hood. Some parameters like format, encoding, bits_per_sample, buffer_size, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's encoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.encoders.AudioEncoder
  warnings.warn(
/workspace/envs/cosyvoice/lib/python3.10/site-packages/torchaudio/_backend/ffmpeg.py:247: UserWarning: torio.io._streaming_media_encoder.StreamingMediaEncoder has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being consolidated into TorchCodec. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release.
  s = torchaudio.io.StreamWriter(uri, format=muxer, buffer_size=buffer_size)
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:05,390 WARNING synthesis text بلا ئەزبەنی، جارێ دا شیڤا ژی بدەینێ. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:36:06,315 INFO synthesis text بلا ئەزبەنی، جارێ دا شیڤا ژی بدەینێ.
2026-10-13 08:36:06,792 INFO yield speech len 0.12, rtf 3.975037733713786
100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:06,838 WARNING synthesis text چەندەک هەنە دەستێ خو دکن ئامیرەتان، ئەوێ گر گوت. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:36:07,760 INFO synthesis text چەندەک هەنە دەستێ خو دکن ئامیرەتان، ئەوێ گر گوت.
2026-10-13 08:36:10,319 INFO yield speech len 3.76, rtf 0.6804920891497998
100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:11,357 INFO synthesis text چیڕوک ڤان گوتنا دبێژن: ِرۆژەکێ ژ ڕۆژان پاشایێ ئامێدیێ گوتە عیسێ دەلا، چ خوشە ل دونیایێ؟
2026-10-13 08:36:15,754 INFO yield speech len 6.76, rtf 0.6504451029399443
100%|██████████| 1/1 [00:05<00:00,  5.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:16,729 INFO synthesis text پشتی سێزدە سالان هێلا ئاسمانیا تورکیا سەر ژ نوی گەشتێن خو بۆ سوریا دەست پێ کرییە.
2026-10-13 08:36:17,315 INFO yield speech len 0.4, rtf 1.4640897512435913
100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:18,252 INFO synthesis text قەرۆ وەختا قەمەرتای سیاربوو، قەمەرتای بن قەرودا ڕوو ئەزمان، ستەیرک پارەڤە دکر.
2026-10-13 08:36:22,172 INFO yield speech len 6.12, rtf 0.6405741171120038
100%|██████████| 1/1 [00:04<00:00,  4.83s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:23,138 INFO synthesis text گاز پرۆما ڕوسی هنارتنا گازێ بۆ وەڵاتێن پولەندا و بولگاریا ڕاوستاند.
2026-10-13 08:36:26,758 INFO yield speech len 5.64, rtf 0.6419085441751683
100%|██████████| 1/1 [00:04<00:00,  4.54s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:27,706 INFO synthesis text بۆ زانین هەر قوتابیەکێ حەزا پشکداربوونێ د پروگرامێ ناڤبری دا هەبیت دشێت ب ڕێکا لینکێ ل خوارێ دیارکری خو تومار بکەت.
2026-10-13 08:36:32,751 INFO yield speech len 8.28, rtf 0.6092846969475493
100%|██████████| 1/1 [00:05<00:00,  5.97s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:32,786 WARNING synthesis text من چ جارا زەلامەک سەرنجراکێشتر ژ می هیوی نەدیتییە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:36:33,721 INFO synthesis text من چ جارا زەلامەک سەرنجراکێشتر ژ می هیوی نەدیتییە.
2026-10-13 08:36:36,061 INFO yield speech len 3.6, rtf 0.6500014331605699
100%|██████████| 1/1 [00:03<00:00,  3.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:37,014 INFO synthesis text ل ڤێرە وان خەلکێ کوشتی و گونەهکاریێت کرین، وان ژنکێن کرین و فروشتین، دوهی حەفت فارسێن کوشتین.
2026-10-13 08:36:41,206 INFO yield speech len 6.76, rtf 0.6199955940246582
100%|██████████| 1/1 [00:05<00:00,  5.12s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:42,145 INFO synthesis text پێنج ژ سەدێ دێ زەکاتێ دەت، و هەکە ئنیەتا وی ب وان سەهمان نە بازرگانی و کرین و فروتن بیت.
2026-10-13 08:36:46,186 INFO yield speech len 6.4, rtf 0.6314553692936897
100%|██████████| 1/1 [00:04<00:00,  4.95s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:47,153 INFO synthesis text بڕیارە سباهی چوارشەمبی رۆژا هەژدە، هەیڤا دەه، سالا دو هزار و سیه و دو جو بایدن، سەروکێ ئەمریکا، سەرەدانا ئیسرائیل بکەت.
2026-10-13 08:36:53,192 INFO yield speech len 9.8, rtf 0.6162570204053606
100%|██████████| 1/1 [00:06<00:00,  6.96s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:54,155 INFO synthesis text قەرار و پەیماندان کو ژ کەسوکارا بخوازیت دەرفەت نەکەفتێ مالێت وان بارکر، چوونە وارەکێ دی.
2026-10-13 08:36:58,723 INFO yield speech len 7.32, rtf 0.6240127190866105
100%|██████████| 1/1 [00:05<00:00,  5.48s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:36:59,664 INFO synthesis text نەنیاس، گوندەکی ل بەر تاڤێ، بێ ئاڤ، گەرم وەک جەهەنەمێیە.
2026-10-13 08:37:02,547 INFO yield speech len 4.52, rtf 0.6378521433973735
100%|██████████| 1/1 [00:03<00:00,  3.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:02,598 WARNING synthesis text جوتیارێ دەولەمەند بکەیف گوتێ؛ گەلەک باشە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:37:03,547 INFO synthesis text جوتیارێ دەولەمەند بکەیف گوتێ؛ گەلەک باشە.
2026-10-13 08:37:05,914 INFO yield speech len 3.6, rtf 0.6576755974027846
100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:05,988 WARNING synthesis text ساندەرسێ روباری؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:37:06,920 INFO synthesis text ساندەرسێ روباری؟
2026-10-13 08:37:07,329 INFO yield speech len 0.08, rtf 5.1022738218307495
100%|██████████| 1/1 [00:01<00:00,  1.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:07,364 WARNING synthesis text ڕوناهیێن کولانێ ل دەرڤەی پەنجەرکێ هەلبوون. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:37:08,274 INFO synthesis text ڕوناهیێن کولانێ ل دەرڤەی پەنجەرکێ هەلبوون.
2026-10-13 08:37:10,684 INFO yield speech len 3.6, rtf 0.6693947315216064
100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:11,636 INFO synthesis text چنکی بەری کوردستان سەرانسەر ببیت دەستێ دەولەتا سەفەوی دا بوو.
2026-10-13 08:37:14,536 INFO yield speech len 4.64, rtf 0.6250078822004385
100%|██████████| 1/1 [00:03<00:00,  3.81s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:14,569 WARNING synthesis text بەس وەرە روینە خارا بێهنا خوە ڤەکە، لەشا منا پیسە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:37:15,462 INFO synthesis text بەس وەرە روینە خارا بێهنا خوە ڤەکە، لەشا منا پیسە.
2026-10-13 08:37:17,903 INFO yield speech len 3.8, rtf 0.6422210367102372
100%|██████████| 1/1 [00:03<00:00,  3.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:18,849 INFO synthesis text د ڤێرە دا ئەڤە ڕامانا وێ چەندێ ناگەهینیت کو لایەنێ ئاشتیخوازیێ بتنێ گرێدای ئایینی بیت.
2026-10-13 08:37:22,988 INFO yield speech len 6.52, rtf 0.6346994016799459
100%|██████████| 1/1 [00:05<00:00,  5.04s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:23,943 INFO synthesis text مە دڤێت ل پێشیا چەند تیرۆژکەکان بێخینە سەر ڕەوشا تەجروبا ئینتیخاباتان.
2026-10-13 08:37:27,552 INFO yield speech len 5.6, rtf 0.6444988931928363
100%|██████████| 1/1 [00:04<00:00,  4.52s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:28,505 INFO synthesis text شیخادی هاتە لالشە خەملی بخەرقێت ڕەشە عەدەویا حال پێ خوەشە.
2026-10-13 08:37:31,686 INFO yield speech len 5.0, rtf 0.636176872253418
100%|██████████| 1/1 [00:04<00:00,  4.10s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:32,635 INFO synthesis text ڕێکخراوا شلومو بودوکیومێنتاریان دیار کر، کریستیانان ب ڕێژا حەفتێ و پێنج ژ سەدێ موسل بجهــ هێلاینە، و هژمارا وان کێم بوویە.
2026-10-13 08:37:38,332 INFO yield speech len 9.16, rtf 0.6218717348107083
100%|██████████| 1/1 [00:06<00:00,  6.61s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:39,259 INFO synthesis text لێ تێ گوتن کو د شەڕەکی ناڤ لەشکەرێن گوشتاسب و تورانیان دە ژیانا خوە وەندا کرییە.
2026-10-13 08:37:43,637 INFO yield speech len 6.72, rtf 0.6514729488463629
100%|██████████| 1/1 [00:05<00:00,  5.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:44,630 INFO synthesis text """کەر و گور"" چیڕوکا شیرەتکاریێیە، یا دەرهەقا حەیوانان دا."
2026-10-13 08:37:47,391 INFO yield speech len 4.12, rtf 0.669978718155796
100%|██████████| 1/1 [00:03<00:00,  3.69s/it]

  bafreen: 25/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:48,434 INFO synthesis text سەروک نێچیرڤان بارزانی ئەڤرۆ دووشەمبیێ پێشوازی ل د. فەریاد فازل عومەر سەروکێ ئینستیتیوتا خواندنا کوردی ل بەرلینێ کر.
2026-10-13 08:37:54,466 INFO yield speech len 9.88, rtf 0.6104988849114792
100%|██████████| 1/1 [00:06<00:00,  6.97s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:55,432 INFO synthesis text شەماسێ وەزیر گوت: و کیژ گەنجینەیا ئەسمانی ژ هەمیا چێترە؟
2026-10-13 08:37:58,612 INFO yield speech len 5.04, rtf 0.6308887686048236
100%|██████████| 1/1 [00:04<00:00,  4.09s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:37:58,738 WARNING synthesis text جوتیاری گوتێ: چاوا تو تێ ناگەهی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:37:59,662 INFO synthesis text جوتیاری گوتێ: چاوا تو تێ ناگەهی؟
2026-10-13 08:38:01,636 INFO yield speech len 2.8, rtf 0.7049458367483957
100%|██████████| 1/1 [00:02<00:00,  2.90s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:01,726 WARNING synthesis text ژ بابێت مەنە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:02,646 INFO synthesis text ژ بابێت مەنە.
2026-10-13 08:38:03,029 INFO yield speech len 0.08, rtf 4.7898948192596436
100%|██████████| 1/1 [00:01<00:00,  1.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:03,063 WARNING synthesis text دایکوبابێن من. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:03,964 INFO synthesis text دایکوبابێن من.
2026-10-13 08:38:05,287 INFO yield speech len 1.68, rtf 0.7873167594273885
100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:05,367 WARNING synthesis text سەیدا، ئەز دێ سەد سواران دەمە ل گەل تە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:06,285 INFO synthesis text سەیدا، ئەز دێ سەد سواران دەمە ل گەل تە.
2026-10-13 08:38:08,432 INFO yield speech len 3.16, rtf 0.6796608997296683
100%|██████████| 1/1 [00:03<00:00,  3.07s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:09,371 INFO synthesis text ماموستا دویماهی پەیاما وە بۆ خواندەڤانێن مەتین چییە؟
2026-10-13 08:38:12,221 INFO yield speech len 4.4, rtf 0.6476549126885154
100%|██████████| 1/1 [00:03<00:00,  3.76s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:13,171 INFO synthesis text مەلکی گوت: ئەوێ شیانێن دفن بلندکرنێ هەبن، شیانێن نزمکرنێ ژی هەنە.
2026-10-13 08:38:17,050 INFO yield speech len 6.0, rtf 0.6465564171473185
100%|██████████| 1/1 [00:04<00:00,  4.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:18,028 INFO synthesis text تشتەکێ ڤەشارتی د لەشێ وێ دا هشیار دبوو، ترسەکا مەزن ژ ناخێ وێ دڤەژاند.
2026-10-13 08:38:21,463 INFO yield speech len 5.48, rtf 0.6267457547849111
100%|██████████| 1/1 [00:04<00:00,  4.37s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:21,498 WARNING synthesis text پێتڤی ناکەت ئەم چ کوردا بکوژین. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:22,422 INFO synthesis text پێتڤی ناکەت ئەم چ کوردا بکوژین.
2026-10-13 08:38:24,437 INFO yield speech len 2.96, rtf 0.6808751338237041
100%|██████████| 1/1 [00:02<00:00,  2.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:24,467 WARNING synthesis text کوڕەک ببوو، ل کیرێ ببوو؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:25,363 INFO synthesis text کوڕەک ببوو، ل کیرێ ببوو؟
2026-10-13 08:38:27,184 INFO yield speech len 2.56, rtf 0.7111318409442902
100%|██████████| 1/1 [00:02<00:00,  2.72s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:28,131 INFO synthesis text نێچیرڤان بارزانی سەروکێ هەرێما کوردستانێ پێشوازی ل هیتوشی ئیشیزوکا، بەرپرسێ نویێ نڤێسینگەها کونسولگەریا ژاپونێ ل هەولێرێ کر.
2026-10-13 08:38:33,742 INFO yield speech len 9.12, rtf 0.6152294706880002
100%|██████████| 1/1 [00:06<00:00,  6.52s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:34,710 INFO synthesis text ل گورەی لێکولینەکا نوی سەرکەفتن ب سەر دەرچکان پەنجەشێرێ کێم دکەت و دبیتە ئەگەر پەنگریاس، گولچیسک و سیهان ژی بهێز دئێخیت.
2026-10-13 08:38:40,375 INFO yield speech len 9.4, rtf 0.6026413592886417
100%|██████████| 1/1 [00:06<00:00,  6.59s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:41,333 INFO synthesis text دیجیتاڵ میدیا سپێدە: چواری هەیڤا حەفت یا ڕۆژا سەربەخویا ویلایەتێن ئێکگرتیێن ئەمریکایە.
2026-10-13 08:38:45,346 INFO yield speech len 6.48, rtf 0.6193775085755336
100%|██████████| 1/1 [00:04<00:00,  4.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:45,419 WARNING synthesis text ق. ک. ب هەلکەفتا ڤیستەڤالا زانکویا دهوک دەردچوو. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:46,345 INFO synthesis text ق. ک. ب هەلکەفتا ڤیستەڤالا زانکویا دهوک دەردچوو.
2026-10-13 08:38:48,968 INFO yield speech len 4.0, rtf 0.655509352684021
100%|██████████| 1/1 [00:03<00:00,  3.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:49,933 INFO synthesis text دەمێ ئەم نڤستین هەر دوو خویشکێت من ڕابوون، ئەز و ئەو گەنج ب نڤین ڤە هاڤێتنە دەریایێ دا.
2026-10-13 08:38:54,130 INFO yield speech len 6.36, rtf 0.6598388998763366
100%|██████████| 1/1 [00:05<00:00,  5.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:54,164 WARNING synthesis text بێکو ئێک وان ببینیت. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:38:55,067 INFO synthesis text بێکو ئێک وان ببینیت.
2026-10-13 08:38:56,474 INFO yield speech len 1.88, rtf 0.7485596423453473
100%|██████████| 1/1 [00:02<00:00,  2.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:38:57,434 INFO synthesis text نوژدارێ یانەیێ، ڕاگەهاندیە کو ڕونالدوی پێدڤی ب بهێنڤەدانێ هەیە، لەورا نەشێت د گەل یانەیێ بچیت بۆ بەغدا.
2026-10-13 08:39:01,950 INFO yield speech len 7.28, rtf 0.6203310175256415
100%|██████████| 1/1 [00:05<00:00,  5.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:02,912 INFO synthesis text تێدا خەلکی هان ددەت ژبۆ ئێکگرتنێ و دبێژیتێ: نەبێژن ئەڤە کوردە، یان تورکە.
2026-10-13 08:39:06,529 INFO yield speech len 5.72, rtf 0.6324138674702678
100%|██████████| 1/1 [00:04<00:00,  4.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:07,540 INFO synthesis text سەروک وەزیرێن بریتانیا ل تەل ئەڤیڤ، ل گەل سەروک وەزیرێن ئسرائیل، بنیامێن نەتەنیاهو د کونگرەیەکێ ڕۆژنامەڤانی دا پشتەڤانیا بریتانیا بۆ ئسرائیل دووپات کر.
2026-10-13 08:39:13,997 INFO yield speech len 10.88, rtf 0.5934818045181386
100%|██████████| 1/1 [00:07<00:00,  7.38s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:14,048 WARNING synthesis text حەمامچی ژی گوت: سوپاس بۆ خوداێ ئەو ژی قاییل بوو. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:39:14,961 INFO synthesis text حەمامچی ژی گوت: سوپاس بۆ خوداێ ئەو ژی قاییل بوو.
2026-10-13 08:39:17,361 INFO yield speech len 3.68, rtf 0.6522916581319725
100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:18,320 INFO synthesis text بۆ نموونە، پروپی د ماوێ ڤەکولینا خو دا بۆ کومەکا چیڕوکێن فولکلوری سێ جورێن جهی دەستنیشان کرینە.
2026-10-13 08:39:22,909 INFO yield speech len 7.4, rtf 0.6201505983198011
100%|██████████| 1/1 [00:05<00:00,  5.52s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:23,838 INFO synthesis text ڤەکولینا (شەڕو جەنگ د هوزانێت کوردی دا)  نڤیسەری مللەتێ کورد وەسا دایە نیاسین کو حەژ شەڕ و پێکدادانا دکەن.
2026-10-13 08:39:28,438 INFO yield speech len 7.48, rtf 0.6150090758175774
100%|██████████| 1/1 [00:05<00:00,  5.50s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:29,380 INFO synthesis text گرنگیا مێژوویا نڤێسینێ ب ڕەنگەک بەربەڵاڤ دزڤریتەڤە بۆ هزارا ئێکێ بەری زایینی.
2026-10-13 08:39:33,284 INFO yield speech len 6.08, rtf 0.6421326022399099
100%|██████████| 1/1 [00:04<00:00,  4.82s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:34,245 INFO synthesis text بۆ چ مێژوو دزڤرن و چاوا گەهشتنە ڤێ ڕادەیا نوکە ل سەر؟
2026-10-13 08:39:37,055 INFO yield speech len 4.4, rtf 0.6387894803827459
100%|██████████| 1/1 [00:03<00:00,  3.73s/it]

  bafreen: 50/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:38,021 INFO synthesis text گێسنی د چاڤێ خو دا نابینیت، دەرزیێ د چاڤێ خەلکی دا دبینیت.
2026-10-13 08:39:40,883 INFO yield speech len 4.64, rtf 0.6168469272810838
100%|██████████| 1/1 [00:03<00:00,  3.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:41,905 INFO synthesis text تاوسێ ل ناڤ ئێزدیا دگێرینن شیرەت و قەول و قەسیدێت ئولێ و دوعا و دروزێت دینی نیشا ئێزدیا دکەن.
2026-10-13 08:39:46,502 INFO yield speech len 7.48, rtf 0.614591269569601
100%|██████████| 1/1 [00:05<00:00,  5.54s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:47,456 INFO synthesis text بەلێ ئەڤە بوو جارا ئێکێ بی کو هێزێت بارزانیا توشی لەشکرەکێ نیزامی ببن ب توپ و جەبە خانەڤە.
2026-10-13 08:39:51,550 INFO yield speech len 6.68, rtf 0.6128474623857144
100%|██████████| 1/1 [00:05<00:00,  5.01s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:52,511 INFO synthesis text ل سەر ڤێ یەکێ هاتە ئاشکەراکرن، کو ئەو تابلو کارێ دەستێ شەڕەفخان ب خوە نە.
2026-10-13 08:39:56,118 INFO yield speech len 5.64, rtf 0.6397101896028993
100%|██████████| 1/1 [00:04<00:00,  4.54s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:39:57,071 INFO synthesis text چونکی دەڤەرا هەکاریا دوو باسکن باسکا راست و باسکا چەپ.
2026-10-13 08:39:59,816 INFO yield speech len 4.24, rtf 0.6473993355373167
100%|██████████| 1/1 [00:03<00:00,  3.67s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:00,750 INFO synthesis text ژبەر وێ ژی ئەو هیڤیا، کو وێ بگهیژنە هەڤ، هەلا زێندی و هشیارە.
2026-10-13 08:40:03,872 INFO yield speech len 4.92, rtf 0.6346868790262113
100%|██████████| 1/1 [00:04<00:00,  4.03s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:04,831 INFO synthesis text پاشی ڤەکولەر دهێتە سەر پراکتیککرنا ئەڤان هەمی بابەتێن دەستنیشان کری د بیاڤێ چیڕوکە شعرێن قەدری جوانێ شاعیری دا.
2026-10-13 08:40:10,023 INFO yield speech len 8.6, rtf 0.603677089824233
100%|██████████| 1/1 [00:06<00:00,  6.11s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:10,957 INFO synthesis text ب ڤێ هەلکەفتا خەمگین ژ خودایێ دلوڤان داخازا پلەیەکا بلندا بەهەشتێ و پاداشتێ زەحمەتێن وی بۆ دکەم.
2026-10-13 08:40:14,959 INFO yield speech len 6.48, rtf 0.6175032368412724
100%|██████████| 1/1 [00:04<00:00,  4.90s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:14,990 WARNING synthesis text مام باکیر، ما ئەوا مە بەری نوکە کری وان پێ زانیە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:40:15,906 INFO synthesis text مام باکیر، ما ئەوا مە بەری نوکە کری وان پێ زانیە؟
2026-10-13 08:40:18,489 INFO yield speech len 4.04, rtf 0.6394802933872337
100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:18,532 WARNING synthesis text سەبر و هەدارێ بدەتە هەمی ئالیان. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:40:19,436 INFO synthesis text سەبر و هەدارێ بدەتە هەمی ئالیان.
2026-10-13 08:40:21,405 INFO yield speech len 2.96, rtf 0.6651361246366758
100%|██████████| 1/1 [00:02<00:00,  2.88s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:22,348 INFO synthesis text من ل بەرە سوزێ بدەمە تە، کو چ جاران ب دویڤ تە نەکەڤم، ئەگەر ئەوا من بڤێت تو بکەی.
2026-10-13 08:40:26,063 INFO yield speech len 5.96, rtf 0.6233569759650518
100%|██████████| 1/1 [00:04<00:00,  4.62s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:27,017 INFO synthesis text لێ د هەڤرکیێن راستین دا، ڕێ یێن چەوت نابن پالپشتێن چ ئارمانجان.
2026-10-13 08:40:29,787 INFO yield speech len 4.44, rtf 0.6237992295273789
100%|██████████| 1/1 [00:03<00:00,  3.70s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:30,727 INFO synthesis text ئێکەتیێ لژنەیا دانوستاندنان پێکئینا و قوباد تالەبانی سەروکێ لژنێیە.
2026-10-13 08:40:34,060 INFO yield speech len 5.16, rtf 0.6459304528642994
100%|██████████| 1/1 [00:04<00:00,  4.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:35,037 INFO synthesis text محەمەدێ تەباتەبایی چوو سەر منبەرێ و کرە گری و بۆ ئەگەرێ سەرهەلدانا خەلکی ل دژی حکومەتێ.
2026-10-13 08:40:39,456 INFO yield speech len 7.08, rtf 0.624179739063069
100%|██████████| 1/1 [00:05<00:00,  5.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:40,447 INFO synthesis text گوهدا دێو گو: قیزێ، ئیرۆ ئەزێ بڤم دووپشک بکەڤم ساپوکا وی.
2026-10-13 08:40:43,531 INFO yield speech len 5.0, rtf 0.6167670249938965
100%|██████████| 1/1 [00:04<00:00,  4.01s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:44,465 INFO synthesis text دانانا پەراوێزان دێ هاریکاریا خواندەڤانی کەت داکو خو پتر دابهێلیتە د دەریایا شێعرێ دا و پتر سەرهەلی جیهانا شاعری ببیت.
2026-10-13 08:40:49,483 INFO yield speech len 8.2, rtf 0.6120105778298728
100%|██████████| 1/1 [00:05<00:00,  5.92s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:50,439 INFO synthesis text تایبەتمەندیێن هوسا ژی دێ کاریگەری ل هەمی جهێن کو ئەو زاروک لێ کار دکەت یان کارێکێ د گەل دکەت ل پاشەرۆژێ.
2026-10-13 08:40:55,317 INFO yield speech len 7.8, rtf 0.6253744394351275
100%|██████████| 1/1 [00:05<00:00,  5.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:40:56,249 INFO synthesis text پاشی گوت: ئەو تشتێ تە گوتییە من ئەی دختور کورێ من لەزێ لێ بکە و کەنگی بیت دروستە.
2026-10-13 08:40:59,995 INFO yield speech len 6.12, rtf 0.6122302775289498
100%|██████████| 1/1 [00:04<00:00,  4.65s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:00,068 WARNING synthesis text کچا وی هێدیکا هاتە نک: باب. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:41:00,979 INFO synthesis text کچا وی هێدیکا هاتە نک: باب.
2026-10-13 08:41:02,738 INFO yield speech len 2.52, rtf 0.6979308431110685
100%|██████████| 1/1 [00:02<00:00,  2.67s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:02,768 WARNING synthesis text پارتا گەلێ تورکمانیا عێراقێ. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:41:03,665 INFO synthesis text پارتا گەلێ تورکمانیا عێراقێ.
2026-10-13 08:41:05,368 INFO yield speech len 2.44, rtf 0.6980666371642567
100%|██████████| 1/1 [00:02<00:00,  2.60s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:06,335 INFO synthesis text تو شەمسی، ئەز قەمەرم، تو خوندکاری، ئەز بابزەرم یا مەلک شێخ سن.
2026-10-13 08:41:09,339 INFO yield speech len 4.48, rtf 0.6705400667020253
100%|██████████| 1/1 [00:03<00:00,  3.92s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:10,270 INFO synthesis text کابرایێ دی خو ژ سەر بەربانکی هاڤێت، بێ هیڤی بریندارە.
2026-10-13 08:41:13,416 INFO yield speech len 4.96, rtf 0.6343845398195328
100%|██████████| 1/1 [00:04<00:00,  4.05s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:13,450 WARNING synthesis text حەچکو وی ڤیا بکەڤت سەر تەنشتێ لێ خو گرت. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:41:14,360 INFO synthesis text حەچکو وی ڤیا بکەڤت سەر تەنشتێ لێ خو گرت.
2026-10-13 08:41:16,463 INFO yield speech len 3.16, rtf 0.6654578673688671
100%|██████████| 1/1 [00:03<00:00,  3.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:16,492 WARNING synthesis text تەنێ بەرێ سپێدا هەتا نیڤرۆیا ئەز ب سەر دکەتم. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:41:17,409 INFO synthesis text تەنێ بەرێ سپێدا هەتا نیڤرۆیا ئەز ب سەر دکەتم.
2026-10-13 08:41:19,944 INFO yield speech len 3.88, rtf 0.6533206738147539
100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:20,871 INFO synthesis text دیسان داخوازێ ژ داواکارێ گشتی دکەین پشتەڤانیا ڕۆژنامەڤانان بکەن، ژبەرکو بابەت گرێدایی بەرژەوەندیا گشتیە.
2026-10-13 08:41:25,797 INFO yield speech len 7.92, rtf 0.6220153786919334
100%|██████████| 1/1 [00:05<00:00,  5.83s/it]

  bafreen: 75/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:26,787 INFO synthesis text شاهـ ژی یێ بێ عەیال بوو ژبلی وێ کچکا دگوتنێ دەیکا سعوودی چ عەیالێت دی نەبوون.
2026-10-13 08:41:30,430 INFO yield speech len 5.72, rtf 0.636928314929242
100%|██████████| 1/1 [00:04<00:00,  4.56s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:31,376 INFO synthesis text سەرەڕایی ڕکەبەریا دوو سێ دەنگەکان، لێ سەیدای فەرمانا خوە بجهئینا و دەنگودوورێ وان خوسەریا خوە وەرگرت.
2026-10-13 08:41:36,244 INFO yield speech len 7.84, rtf 0.6208859232007241
100%|██████████| 1/1 [00:05<00:00,  5.78s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:36,281 WARNING synthesis text پێکولا بدەستڤەئینانا پالپشتیا دەرونی بکە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:41:37,209 INFO synthesis text پێکولا بدەستڤەئینانا پالپشتیا دەرونی بکە.
2026-10-13 08:41:39,429 INFO yield speech len 3.36, rtf 0.6605771325883412
100%|██████████| 1/1 [00:03<00:00,  3.15s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:40,362 INFO synthesis text ژنەک بیت هەر دەمێ پشتەڤان و هاندەر و جهەکێ بیت بۆ زەلامێ خو.
2026-10-13 08:41:43,784 INFO yield speech len 5.32, rtf 0.6431593034500466
100%|██████████| 1/1 [00:04<00:00,  4.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:44,747 INFO synthesis text موکومیا پەیوەندییێن جڤاکی و بەربەڵاڤەیا گیانێ هاریکاریێ د ناڤ تەخێن جڤاکی دا.
2026-10-13 08:41:48,491 INFO yield speech len 5.84, rtf 0.6410496692134909
100%|██████████| 1/1 [00:04<00:00,  4.66s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:48,542 WARNING synthesis text مخابن، ئەرێ، ئەز دبێژم هزرا منا راستە. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:41:49,453 INFO synthesis text مخابن، ئەرێ، ئەز دبێژم هزرا منا راستە.
2026-10-13 08:41:52,059 INFO yield speech len 3.96, rtf 0.6581830255913012
100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:53,031 INFO synthesis text دەمێ کو سەربازی گوهـ ل ڤێ ئاخفتنێ بووی پێنگاڤەکێ پاشڤە چوو و گوت: ئاهـ.
2026-10-13 08:41:56,590 INFO yield speech len 5.48, rtf 0.6495535373687744
100%|██████████| 1/1 [00:04<00:00,  4.50s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:41:57,562 INFO synthesis text بەلێ میرێ من ئەڤە کورێ تە میرزایە و ئەز بویکا تە مە و کچا تە و ژنا تە ل ئالیێ مالێنە.
2026-10-13 08:42:01,819 INFO yield speech len 6.68, rtf 0.6372483904490214
100%|██████████| 1/1 [00:05<00:00,  5.18s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:02,787 INFO synthesis text خویندەڤانێ ڕەسەن ژ سەردەمەکی بۆ سەردەمەکێ دیتر یێ جودایە، هەروەسا ئەڤ خویندەڤانە د هەمی سەردەمێن مێژوویێ ژی دا دژێک جودانە.
2026-10-13 08:42:08,978 INFO yield speech len 10.16, rtf 0.609407955267298
100%|██████████| 1/1 [00:07<00:00,  7.12s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:09,947 INFO synthesis text سڤکبوون و بێ بهایا مروڤی کو مروڤ ڕێزێ بۆ خو نەهێلیت ژ ئەنجامێ کارێن فهێت و نەدهەژی.
2026-10-13 08:42:13,822 INFO yield speech len 6.08, rtf 0.6373615641342966
100%|██████████| 1/1 [00:04<00:00,  4.80s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:14,771 INFO synthesis text پشترە تەرمێ وی هاتە ڤەگوهاستن بۆ نوژداریا داد ل زاخو بۆ مەرەما تویکاریا نوژداری.
2026-10-13 08:42:18,341 INFO yield speech len 5.64, rtf 0.6330165879946229
100%|██████████| 1/1 [00:04<00:00,  4.48s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:19,307 INFO synthesis text منبج باژێرەکێ کوردیە، دکەڤیتە ڕۆژئاڤایێ ڕویبارێ فوراتی و ل گەل کوبانێ هەڤسنورە.
2026-10-13 08:42:23,277 INFO yield speech len 6.04, rtf 0.6572988649077762
100%|██████████| 1/1 [00:04<00:00,  4.90s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:24,241 INFO synthesis text مێر ڕابوون تەبایی چوونە سەرێ چیای سەکنین بەرێ خودانە بای.
2026-10-13 08:42:27,120 INFO yield speech len 4.52, rtf 0.63700554645167
100%|██████████| 1/1 [00:03<00:00,  3.80s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:28,061 INFO synthesis text لێ نموونێن وی تنێ ڕەنگەکێ شێعرێن سەربەست پەسەندکەت، کو ئەو ژی ئەو جورن ئەڤێن بنیاتێ وان یێ ڕیتمی سادە.
2026-10-13 08:42:32,991 INFO yield speech len 7.6, rtf 0.6487317461716502
100%|██████████| 1/1 [00:05<00:00,  5.84s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:33,954 INFO synthesis text ڤی عەگیدی بگرن زورداریێ لێ بکەن نەگرن مێرەکێ باشە، ئەڤێ سترانێ پێت بێژن.
2026-10-13 08:42:37,797 INFO yield speech len 6.12, rtf 0.6279844863742006
100%|██████████| 1/1 [00:04<00:00,  4.76s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:38,807 INFO synthesis text پشتی شوڕەشا ئیسلامی ل ئیرانێ د زانینگەهێ دە دەرفەتا خەباتێ نەدیتییە و هاتییە فرەنسا.
2026-10-13 08:42:43,005 INFO yield speech len 6.92, rtf 0.6067420705894514
100%|██████████| 1/1 [00:05<00:00,  5.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:43,942 INFO synthesis text کومکوژیا جوهیان ئەنجامێن هزرێن نەژادی - ئایدولوژیا ئادولف هێتلەر بوو.
2026-10-13 08:42:47,635 INFO yield speech len 5.84, rtf 0.6324481474210139
100%|██████████| 1/1 [00:04<00:00,  4.60s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:47,675 WARNING synthesis text دەستویری بیت، ئەز دێ پیچەکێ دەرکەڤم. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:42:48,584 INFO synthesis text دەستویری بیت، ئەز دێ پیچەکێ دەرکەڤم.
2026-10-13 08:42:50,824 INFO yield speech len 3.28, rtf 0.6826508335950898
100%|██████████| 1/1 [00:03<00:00,  3.15s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:51,758 INFO synthesis text عامری: پێدڤیە یەکسانی د ناڤبەرا هەمی فەرمانبەران دا ل عێراقێ بۆ دابەشکرنا مووچەیان هەبیت.
2026-10-13 08:42:55,933 INFO yield speech len 6.64, rtf 0.62867966761072
100%|██████████| 1/1 [00:05<00:00,  5.08s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:42:56,871 INFO synthesis text ژنا وی گوتێ، دیارە ژ کەیفان دا یێ دین بووی، دویر نینە سوباهی ئاقلێ وی بهێتە سەری ڤە، پشتی تێر بنڤیت.
2026-10-13 08:43:01,724 INFO yield speech len 7.56, rtf 0.6419044007699957
100%|██████████| 1/1 [00:05<00:00,  5.76s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:02,659 INFO synthesis text ب چێکرنا تو کەسی قاییل نەدبوو، ب خوە چێدکر و ب قەدەحەکە کونیاکا ئەرمەنیستانێ دخوەر.
2026-10-13 08:43:06,808 INFO yield speech len 6.64, rtf 0.624877932560013
100%|██████████| 1/1 [00:05<00:00,  5.05s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:07,776 INFO synthesis text کی هەبوو ل ڤی وەڵاتی دلێ وان نەشکەست بیت، چ کوردەکە ئازار نەدیتبیت ژ ئەگەرێ یازدەی ئوکتوبەرێ.
2026-10-13 08:43:12,423 INFO yield speech len 7.12, rtf 0.6526364369338817
100%|██████████| 1/1 [00:05<00:00,  5.59s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:13,371 INFO synthesis text تونی کروس بڕیار دا بۆ سالەکا دی بمینیتە د ناڤ ڕێزێن ڕیال مەدرید دا.
2026-10-13 08:43:16,402 INFO yield speech len 4.8, rtf 0.6315441926320394
100%|██████████| 1/1 [00:03<00:00,  3.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:17,355 INFO synthesis text من گەلەک جاران ژی ب ئالیێ شارستانی و کەلەپوری ڤە گرێددا کو لێکولینا تابلویان ئامورێن موزیکێ بوون.
2026-10-13 08:43:21,801 INFO yield speech len 7.04, rtf 0.6316582587632266
100%|██████████| 1/1 [00:05<00:00,  5.36s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:21,849 WARNING synthesis text پاشی جارەک دی ماریف ل هوشەنگی ڤەدگەریت. too short than prompt text You are a helpful assistant.<|endofprompt|>ئەحو، ئەڤە چ سەرمایەکا دژوارە ئەڤ سالە، یا تژی بەفر و بارانە!, this may lead to bad performance
2026-10-13 08:43:22,751 INFO synthesis text پاشی جارەک دی ماریف ل هوشەنگی ڤەدگەریت.
2026-10-13 08:43:24,898 INFO yield speech len 3.16, rtf 0.6795571574681921
100%|██████████| 1/1 [00:03<00:00,  3.05s/it]

  bafreen: 100/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:25,872 INFO synthesis text پاشی باب وکالێت مە یێت هاتینە سوریێ، ژ وێڕێ یێت هاتینە شنگار، ل داویێ ئەمێ ل ڤێرێ ئاکنجی بووین.
2026-10-13 08:43:30,270 INFO yield speech len 7.0, rtf 0.6282822404588971
100%|██████████| 1/1 [00:05<00:00,  5.31s/it]

  bafreen: 101/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:30,403 WARNING synthesis text زنجی و کوڕکێ زیرەکێ من بۆ خو کەیفێ دکن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:43:31,770 INFO synthesis text زنجی و کوڕکێ زیرەکێ من بۆ خو کەیفێ دکن.
2026-10-13 08:43:34,206 INFO yield speech len 3.48, rtf 0.7002028240554634
100%|██████████| 1/1 [00:03<00:00,  3.81s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:35,585 INFO synthesis text ئێکی هەیڤا گولانا هزار و نەهسەد و پێنجی و نەهـێ: بەڵاڤبوونا ڕوژنامەیا ئازادی.
2026-10-13 08:43:39,171 INFO yield speech len 5.44, rtf 0.6593202843385584
100%|██████████| 1/1 [00:04<00:00,  4.93s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:39,220 WARNING synthesis text تابلویێن من ئەڤ ڕوخسارە بجیهـ هیشتن و بەر ب هولا پێشانگەهێ کەتنە ڕێ. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:43:40,556 INFO synthesis text تابلویێن من ئەڤ ڕوخسارە بجیهـ هیشتن و بەر ب هولا پێشانگەهێ کەتنە ڕێ.
2026-10-13 08:43:43,771 INFO yield speech len 4.8, rtf 0.669720321893692
100%|██████████| 1/1 [00:04<00:00,  4.56s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:45,157 INFO synthesis text ڕاهێنەرێ فرەنسا ڕەخنەیێ ل بڕیارا ئەنجامدانا موندیالا دوو هزار و سیهـ ل شەش وەڵاتان دگریت.
2026-10-13 08:43:49,336 INFO yield speech len 6.44, rtf 0.6488116631596724
100%|██████████| 1/1 [00:05<00:00,  5.52s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:50,697 INFO synthesis text پێغەمبەر (سلاڤێت خودێ لێ بن) دبێژیت: زەکات بۆ مروڤێ زەنگین نەدورستە، ئەبو داوودی و ترمزی ڤەگێرایە.
2026-10-13 08:43:55,462 INFO yield speech len 7.44, rtf 0.6405028284236949
100%|██████████| 1/1 [00:06<00:00,  6.10s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:43:56,854 INFO synthesis text پشتی سەججادی زڤڕیەڤە بەرسڤا پرسیارێن مەلا ئەنوەری ب نڤیسین دایە و هەمان بەرسڤ د پەڕتووکێ دا بەڵاڤ کرینە.
2026-10-13 08:44:01,803 INFO yield speech len 7.76, rtf 0.6378032190283549
100%|██████████| 1/1 [00:06<00:00,  6.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:03,251 INFO synthesis text د شوڕەشا نها دا، وەها دهێت بەرچاڤ کو شێخ دەورێ مێرێ پیروزێ بارزانیان ژبۆ ئاشتی و ل هەڤهاتنێ دگێرت.
2026-10-13 08:44:08,035 INFO yield speech len 7.56, rtf 0.6328144401469559
100%|██████████| 1/1 [00:06<00:00,  6.16s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:08,069 WARNING synthesis text حەمامچی گوت: قوناغا شەش ڕۆژا. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:44:09,393 INFO synthesis text حەمامچی گوت: قوناغا شەش ڕۆژا.
2026-10-13 08:44:11,720 INFO yield speech len 3.24, rtf 0.7183746791180269
100%|██████████| 1/1 [00:03<00:00,  3.66s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:13,079 INFO synthesis text ژبەر ڤێ چەندێ نویخازیا کوردی ئەنجامەک بوو بۆ وێ گرنگیدانێ ب دەستکەفتیێن ڕەخنا ڕۆژئاڤایی.
2026-10-13 08:44:17,549 INFO yield speech len 6.88, rtf 0.649737133536228
100%|██████████| 1/1 [00:05<00:00,  5.80s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:18,943 INFO synthesis text دیار ژی کرییە، ئەو ماددەیە هاریکاریا باشترکرنا دەرونی، هزرکرن و لڤینێ دکەت.
2026-10-13 08:44:23,021 INFO yield speech len 6.52, rtf 0.6254303674756384
100%|██████████| 1/1 [00:05<00:00,  5.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:24,381 INFO synthesis text پێشبینیا مە بۆ بەرهەمێن گەنمی د ئەڤ سالە دا سەد و بیست هزار تەنێن گەنمیە ئەڤە ژی ڕێژەکا باشە بۆ بەرهەمێ ئەڤ سالە.
2026-10-13 08:44:29,324 INFO yield speech len 7.84, rtf 0.6304793211878562
100%|██████████| 1/1 [00:06<00:00,  6.27s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:29,358 WARNING synthesis text تو هندەک ژ دوعایێت ل سەر جەنازەی دهێنە کرن بۆ مە نابێژی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:44:30,679 INFO synthesis text تو هندەک ژ دوعایێت ل سەر جەنازەی دهێنە کرن بۆ مە نابێژی؟
2026-10-13 08:44:33,739 INFO yield speech len 4.64, rtf 0.6595226711240308
100%|██████████| 1/1 [00:04<00:00,  4.39s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:33,772 WARNING synthesis text تەنهانیسا نوکە نێچیرڤانێ دەریایێت کویر ولەزوکە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:44:35,096 INFO synthesis text تەنهانیسا نوکە نێچیرڤانێ دەریایێت کویر ولەزوکە.
2026-10-13 08:44:37,761 INFO yield speech len 3.96, rtf 0.6728742459807733
100%|██████████| 1/1 [00:03<00:00,  3.99s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:37,792 WARNING synthesis text رۆژا نوو هونەرمەندان پشتی هوستایەکی موزیکا کوردی وەها گوت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:44:39,123 INFO synthesis text رۆژا نوو هونەرمەندان پشتی هوستایەکی موزیکا کوردی وەها گوت.
2026-10-13 08:44:42,091 INFO yield speech len 4.52, rtf 0.6565459006655533
100%|██████████| 1/1 [00:04<00:00,  4.30s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:43,474 INFO synthesis text باغچەڤان دکاریت کولیلکا تەحلیشکێ جوان کەت و بخەملینیت، بەلێ ژەهرا وێ هەر دێ تێدا مینیت.
2026-10-13 08:44:48,070 INFO yield speech len 7.16, rtf 0.641980617405982
100%|██████████| 1/1 [00:05<00:00,  5.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:48,117 WARNING synthesis text ژبەرکو سستەمێ دخواست ل گور داخوازێن وان کارێن هونەری پێک بێن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:44:49,449 INFO synthesis text ژبەرکو سستەمێ دخواست ل گور داخوازێن وان کارێن هونەری پێک بێن.
2026-10-13 08:44:52,692 INFO yield speech len 4.84, rtf 0.6701629023906613
100%|██████████| 1/1 [00:04<00:00,  4.58s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:52,783 WARNING synthesis text خەلک ل جهێن تایبەت پیروزگەهـ و پەرستنێ کومبووینە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:44:54,154 INFO synthesis text خەلک ل جهێن تایبەت پیروزگەهـ و پەرستنێ کومبووینە.
2026-10-13 08:44:56,905 INFO yield speech len 4.12, rtf 0.6679041871746767
100%|██████████| 1/1 [00:04<00:00,  4.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:44:58,275 INFO synthesis text دەرگەهڤانی گوت: ئەزبەنی خودانێ وا گەنجەکێ لاوتازەیە ژ کورێت بازرگانانە، یێ شکل ماقویلە.
2026-10-13 08:45:02,650 INFO yield speech len 7.04, rtf 0.621363723819906
100%|██████████| 1/1 [00:05<00:00,  5.71s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:04,041 INFO synthesis text بلەز و بەز جلێن خوە هاڤیتنە سەر خوە و دەرکەت، لێ خوەزی خواست دەرنەکەتبا.
2026-10-13 08:45:08,149 INFO yield speech len 6.44, rtf 0.637816716425167
100%|██████████| 1/1 [00:05<00:00,  5.47s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:09,553 INFO synthesis text بەرجەستەکرنا هزروبیرێن کوردایەتیێ د ئەدەبێ دا پتر چوون بۆ بەرەڤ تەوژمێ ڕیالیزما شوڕەشگێرانە.
2026-10-13 08:45:14,039 INFO yield speech len 7.16, rtf 0.6264524419880446
100%|██████████| 1/1 [00:05<00:00,  5.83s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:15,383 INFO synthesis text پەیڤدارێ حکومەتێ: مە نڤیسارەک ل دوور شایستەیێن دارایی یێن هەرێمێ ئاراستەی بەغدا کرییە.
2026-10-13 08:45:19,239 INFO yield speech len 6.0, rtf 0.6426074107487997
100%|██████████| 1/1 [00:05<00:00,  5.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:20,586 INFO synthesis text د هێرشەکا ئەسمانی یا تورکیا دا نەهـ ئەندامێن خێزانەکا کورد گیانێن خو ژ دەست دان.
2026-10-13 08:45:24,283 INFO yield speech len 5.56, rtf 0.664925918304663
100%|██████████| 1/1 [00:05<00:00,  5.01s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:25,662 INFO synthesis text راستی ئەوە کو بزاڤێن سەروک نێچیرڤان بارزانی بۆ ئاڤاکرنا پرێن باوەریێ دشێن وەک نموونەیەکا دەگمەن ل ڕۆژهەلاتا ناڤین بهێنە دیتن.
2026-10-13 08:45:30,475 INFO yield speech len 7.64, rtf 0.6299178637759224
100%|██████████| 1/1 [00:06<00:00,  6.15s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:31,849 INFO synthesis text دیجیتاڵ میدیا سپێدە: کەس و کارێن چالاکڤانێن دهوکێ یێن گرتی ل هەمبەر پەڕلەمانێ کوردستانێ خرڤە بوون و داخوازا ئازادکرنا وان دکەن.
2026-10-13 08:45:37,502 INFO yield speech len 9.32, rtf 0.6065157094226886
100%|██████████| 1/1 [00:06<00:00,  6.98s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:38,862 INFO synthesis text چوون بەر دەرێ سولەیمانی وان و گوتێ:  نوبا کورێ هەوەیە، دڤێت بۆ نەهینگی ببەین، دا بازرگان بچیت.
2026-10-13 08:45:43,168 INFO yield speech len 6.64, rtf 0.648363562951605
100%|██████████| 1/1 [00:05<00:00,  5.63s/it]

  abdullah: 25/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:44,552 INFO synthesis text پسیار ڤێرێ ئەڤەیە حەدیسێت دەستویردانا نڤێسانێ و نەهێلانا نڤێسانێ دێ چاوا ئێخینە بەرێک و دێ چاوا کەڤنە بەرێک؟
2026-10-13 08:45:49,653 INFO yield speech len 8.04, rtf 0.6344362870970769
100%|██████████| 1/1 [00:06<00:00,  6.43s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:51,015 INFO synthesis text پیرەمێری دەستێ وی گرت و گوتێ: پاشایێ هێژا، ڕۆژێت خوش یێ ل بەراهیا تە، ژیانەکا خوش دێ بەیە سەر.
2026-10-13 08:45:55,378 INFO yield speech len 6.96, rtf 0.6268430372764324
100%|██████████| 1/1 [00:05<00:00,  5.70s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:45:55,424 WARNING synthesis text دزیکەرا گا برە د ناڤ دارستانێ دا ڤەکوشت و گورا، گوشتێ وی ل خو ژێکرا کر. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:45:56,752 INFO synthesis text دزیکەرا گا برە د ناڤ دارستانێ دا ڤەکوشت و گورا، گوشتێ وی ل خو ژێکرا کر.
2026-10-13 08:46:01,015 INFO yield speech len 6.64, rtf 0.6420273737735059
100%|██████████| 1/1 [00:05<00:00,  5.60s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:02,356 INFO synthesis text ب پلە سێ ل گورەی پیڤەرێ ڕێختەر ل پارێزگەها میسان ل باشورێ ڕۆژهەلاتا عێراقێ دایە.
2026-10-13 08:46:05,944 INFO yield speech len 5.48, rtf 0.6547390109431134
100%|██████████| 1/1 [00:04<00:00,  4.90s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:07,286 INFO synthesis text پرکرنا کەلێنا د ناڤبەرا ئەکادیمیا و سیاسەتدانانێ دا بۆ باشترکرنا سیستەمێ یاسایی یێ عیراقێ.
2026-10-13 08:46:11,475 INFO yield speech len 6.68, rtf 0.6270542830050349
100%|██████████| 1/1 [00:05<00:00,  5.50s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:11,518 WARNING synthesis text سلاڤ ل تەڤا مشەختێت هونەری بن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:46:12,849 INFO synthesis text سلاڤ ل تەڤا مشەختێت هونەری بن.
2026-10-13 08:46:14,946 INFO yield speech len 2.84, rtf 0.7384799735646853
100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:14,978 WARNING synthesis text ڕزگار، زاخویی بوو و ژ ستافێ سەرەکی یێن ڤێ گوڤارێ بوو ژبۆ دەمەکێ درێژ. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:46:16,307 INFO synthesis text ڕزگار، زاخویی بوو و ژ ستافێ سەرەکی یێن ڤێ گوڤارێ بوو ژبۆ دەمەکێ درێژ.
2026-10-13 08:46:20,115 INFO yield speech len 5.96, rtf 0.6389456307327988
100%|██████████| 1/1 [00:05<00:00,  5.14s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:20,146 WARNING synthesis text دبێژن ئینسانا شیرێ خاڤ مێتیە، ب راستی ژی وەهایە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:46:21,457 INFO synthesis text دبێژن ئینسانا شیرێ خاڤ مێتیە، ب راستی ژی وەهایە.
2026-10-13 08:46:24,365 INFO yield speech len 4.24, rtf 0.6858572082699469
100%|██████████| 1/1 [00:04<00:00,  4.22s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:25,744 INFO synthesis text پەیڤەکا دی بێژی، دێ ئەنجامەکێ وەسا بینی کو چ جاران د خەونێن خۆ دا ژی تە پێشبینی نەکربیت.
2026-10-13 08:46:30,026 INFO yield speech len 6.68, rtf 0.641042208243273
100%|██████████| 1/1 [00:05<00:00,  5.63s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:31,363 INFO synthesis text بێ پلاندانان و هزرکرن، چ مالێ هەی کرە د هندە کاران دا؛ هەمی پویچ و پەلاچە بوو.
2026-10-13 08:46:35,308 INFO yield speech len 6.0, rtf 0.657539963722229
100%|██████████| 1/1 [00:05<00:00,  5.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:35,342 WARNING synthesis text ژبلی خودێ مەزن، هەوە هندەک خودێت دن هەنە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:46:36,649 INFO synthesis text ژبلی خودێ مەزن، هەوە هندەک خودێت دن هەنە؟
2026-10-13 08:46:39,313 INFO yield speech len 3.84, rtf 0.693726104994615
100%|██████████| 1/1 [00:03<00:00,  3.98s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:39,347 WARNING synthesis text دوو ئاخفتن ژ سێربەندەکی خرابترە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:46:40,656 INFO synthesis text دوو ئاخفتن ژ سێربەندەکی خرابترە.
2026-10-13 08:46:43,839 INFO yield speech len 4.72, rtf 0.6742076348450224
100%|██████████| 1/1 [00:04<00:00,  4.50s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:45,183 INFO synthesis text د زمانێ لاتینی دا دگوتە هەلبەستان کارمینا، ئەڤە ئیشارەتەکە ڤەدگەریتە بکارئینانا ئاوێردان.
2026-10-13 08:46:49,607 INFO yield speech len 6.88, rtf 0.6429487882658492
100%|██████████| 1/1 [00:05<00:00,  5.74s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:50,957 INFO synthesis text دەمەک ل ڤر دمینە، لێ پشترە ژبەر خەلایێ دیسا کوچ دکە و دچە مصرێ، وەڵاتێ فیرعەونان.
2026-10-13 08:46:55,361 INFO yield speech len 7.16, rtf 0.6149954636003718
100%|██████████| 1/1 [00:05<00:00,  5.72s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:46:55,418 WARNING synthesis text چاڤێ وان ل ڤێ دەولەمەندیا مەیە، ئادەمیزاد دخوازن مە تالان بکەن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:46:56,748 INFO synthesis text چاڤێ وان ل ڤێ دەولەمەندیا مەیە، ئادەمیزاد دخوازن مە تالان بکەن.
2026-10-13 08:47:00,214 INFO yield speech len 5.2, rtf 0.6666650221898005
100%|██████████| 1/1 [00:04<00:00,  4.80s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:00,249 WARNING synthesis text ژبۆ شووشتنا، ژەنگ و قرێژا گوندێ مە خوزی ئەز چیڕوکەک بامە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:47:01,558 INFO synthesis text ژبۆ شووشتنا، ژەنگ و قرێژا گوندێ مە خوزی ئەز چیڕوکەک بامە.
2026-10-13 08:47:04,912 INFO yield speech len 5.12, rtf 0.655090156942606
100%|██████████| 1/1 [00:04<00:00,  4.67s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:04,965 WARNING synthesis text ژ ئارمانجێن ڤی پڕوژەی پەیداکرنا ژیدەرەکێ وزێ ب کێمترین بها. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:47:06,291 INFO synthesis text ژ ئارمانجێن ڤی پڕوژەی پەیداکرنا ژیدەرەکێ وزێ ب کێمترین بها.
2026-10-13 08:47:09,510 INFO yield speech len 5.0, rtf 0.6439538478851319
100%|██████████| 1/1 [00:04<00:00,  4.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:09,546 WARNING synthesis text رۆژنامەڤانیا دیجیتاڵ، ڕولێ ڕۆژنامەڤانیا کاغەزی پاشگوهـ ناکەت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:47:10,861 INFO synthesis text رۆژنامەڤانیا دیجیتاڵ، ڕولێ ڕۆژنامەڤانیا کاغەزی پاشگوهـ ناکەت.
2026-10-13 08:47:13,967 INFO yield speech len 4.6, rtf 0.6750070012134055
100%|██████████| 1/1 [00:04<00:00,  4.42s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:14,000 WARNING synthesis text جەژنا مە یا مەزنە، نابیت کەسێ بیانی تێدا ئامادە ببیت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:47:15,346 INFO synthesis text جەژنا مە یا مەزنە، نابیت کەسێ بیانی تێدا ئامادە ببیت.
2026-10-13 08:47:18,063 INFO yield speech len 4.0, rtf 0.6792405247688293
100%|██████████| 1/1 [00:04<00:00,  4.07s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:18,093 WARNING synthesis text پاشی ژ دارا هاتە خوارا و دەستا خو د ستویێ وی وەراند و ماچیکر. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:47:19,422 INFO synthesis text پاشی ژ دارا هاتە خوارا و دەستا خو د ستویێ وی وەراند و ماچیکر.
2026-10-13 08:47:22,750 INFO yield speech len 5.12, rtf 0.6499762646853924
100%|██████████| 1/1 [00:04<00:00,  4.66s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:24,111 INFO synthesis text راستە، دڤێت هوزانڤان د ناڤ جەرگێ شوڕەشێ دا بژیت دا بشێت ئازریان و هەلچوونێن خو یێن دەرونی ب ڕەنگەکێ راست و دروست دەرببریت.
2026-10-13 08:47:29,801 INFO yield speech len 9.16, rtf 0.6212117890603678
100%|██████████| 1/1 [00:07<00:00,  7.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:31,148 INFO synthesis text سپێدەهیا ئەڤرۆ ڕەجەب تەیب ئەردوگان، سەروک کومارێ تورکیا تویتەک ب ناڤێ (برایێن من یێن کورد یێن خوشتڤی) بەڵاڤ کر.
2026-10-13 08:47:35,900 INFO yield speech len 7.52, rtf 0.6319085651255669
100%|██████████| 1/1 [00:06<00:00,  6.06s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:37,266 INFO synthesis text دیجیتاڵ میدیا سپێدە: کومسیونا هەلبژارتنێن عێراقێ: سوباهی چوارشەمبی بانگەشەیا هەلبژارتنان دێ دەست پێ کەت.
2026-10-13 08:47:42,320 INFO yield speech len 7.96, rtf 0.6349520467633578
100%|██████████| 1/1 [00:06<00:00,  6.38s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:43,666 INFO synthesis text دیسان ناڤێ ڕوستەم هەروەکی د سەرهاتیا ئەڤسانا ڕوستەمێ زالێ دا ئەڤ ناڤە بوویە جەڤەنگ بۆ هێز و شیانێ.
2026-10-13 08:47:48,313 INFO yield speech len 7.28, rtf 0.6383034881654677
100%|██████████| 1/1 [00:05<00:00,  5.96s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:49,651 INFO synthesis text ژنکا تورک گوت، هەوە دڤێت هەتکا ڤان هەر دوو زاروکا ببەن: ئەز دوو هزار زێرا پێ ددەم.
2026-10-13 08:47:53,491 INFO yield speech len 5.76, rtf 0.6667924010091358
100%|██████████| 1/1 [00:05<00:00,  5.15s/it]

  abdullah: 50/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:47:55,134 INFO synthesis text ئێڤارێ واختا ڕازانێ گێلانفروزایێ گۆ: دە قیزکا دەلال، من شەرم نەکە، وێ چارشەڤێ ڤەکە، کو ئەم ڕازێن.
2026-10-13 08:48:00,038 INFO yield speech len 7.72, rtf 0.6351701953868174
100%|██████████| 1/1 [00:06<00:00,  6.47s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:01,382 INFO synthesis text ڕاپرسین ژ لایێ کومسیونا ڕاپرسینا باشورێ سودانی و ب هەڤکاری د گەل حکومەتا باشورێ سودانێ و حکومەتا نەتەوەیی بهێتە ڕێکخستن.
2026-10-13 08:48:07,224 INFO yield speech len 9.28, rtf 0.6295558707467441
100%|██████████| 1/1 [00:07<00:00,  7.16s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:07,257 WARNING synthesis text پشتی چەند ڕۆژەکان بەرسڤ بۆ وان هات. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:08,556 INFO synthesis text پشتی چەند ڕۆژەکان بەرسڤ بۆ وان هات.
2026-10-13 08:48:10,282 INFO yield speech len 2.44, rtf 0.7071877112154101
100%|██████████| 1/1 [00:03<00:00,  3.03s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:10,325 WARNING synthesis text برایێ بچووک گوت، ئەز دزانم ئەم دێ چاوا دیارکەین. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:11,646 INFO synthesis text برایێ بچووک گوت، ئەز دزانم ئەم دێ چاوا دیارکەین.
2026-10-13 08:48:14,179 INFO yield speech len 3.72, rtf 0.6810811258131457
100%|██████████| 1/1 [00:03<00:00,  3.86s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:15,555 INFO synthesis text پارێزگارێ دهوکێ داخواز کر کو هەوا بانگەشێ ب ئارامی و ل دویڤ یاسا و ڕێنمایێن کومسیونا بلندا هەلبژارتنان بهێتە ئەنجامدان.
2026-10-13 08:48:20,662 INFO yield speech len 8.0, rtf 0.6383824348449707
100%|██████████| 1/1 [00:06<00:00,  6.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:22,048 INFO synthesis text پاشی کوڕک ب باڤێ خوە ڕا تەڤایی مالێ ددنە هەڤ، خوارنێ چێدکن و پشتی خوارنێ ئەو دەردانا دشو.
2026-10-13 08:48:26,697 INFO yield speech len 7.2, rtf 0.645727879471249
100%|██████████| 1/1 [00:05<00:00,  5.99s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:26,747 WARNING synthesis text تو ژی دزانی یا بێ گونەهە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:28,068 INFO synthesis text تو ژی دزانی یا بێ گونەهە.
2026-10-13 08:48:29,700 INFO yield speech len 2.24, rtf 0.7282395448003496
100%|██████████| 1/1 [00:02<00:00,  2.96s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:29,755 WARNING synthesis text دیارە ئەزم یێکو تە دوەستینت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:31,082 INFO synthesis text دیارە ئەزم یێکو تە دوەستینت.
2026-10-13 08:48:33,151 INFO yield speech len 2.84, rtf 0.7286402541147152
100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:33,184 WARNING synthesis text حاکم: دەستە برایێ من بریندارە، دڤێت تو ژی ل وی ببی نوبەدار. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:34,520 INFO synthesis text حاکم: دەستە برایێ من بریندارە، دڤێت تو ژی ل وی ببی نوبەدار.
2026-10-13 08:48:37,495 INFO yield speech len 4.48, rtf 0.6640263966151646
100%|██████████| 1/1 [00:04<00:00,  4.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:37,545 WARNING synthesis text بێ گومان ڤێ ڕوناهیێ کاری من بزەحمەت ئێخست. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:38,875 INFO synthesis text بێ گومان ڤێ ڕوناهیێ کاری من بزەحمەت ئێخست.
2026-10-13 08:48:41,781 INFO yield speech len 4.28, rtf 0.6787736282170376
100%|██████████| 1/1 [00:04<00:00,  4.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:43,149 INFO synthesis text خێرا کو ل گیانێ مریان تێ دایین بەرپرسیاریا وان سڤک دکە و دکەڤە بەر گونەهێن وان.
2026-10-13 08:48:47,398 INFO yield speech len 6.76, rtf 0.6284634742511095
100%|██████████| 1/1 [00:05<00:00,  5.58s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:47,441 WARNING synthesis text بەلێ بزەحمەت تێ دگەهشت، چ نەخواندیە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:48,763 INFO synthesis text بەلێ بزەحمەت تێ دگەهشت، چ نەخواندیە.
2026-10-13 08:48:50,816 INFO yield speech len 2.88, rtf 0.7127934859858619
100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:52,165 INFO synthesis text عەڤدال لاڤایا ل ڕێنجبەرا دکە: ئەوی قولنگی بدنە من، ئەو ژی مینا من بریندارە.
2026-10-13 08:48:55,986 INFO yield speech len 5.8, rtf 0.6587467933523244
100%|██████████| 1/1 [00:05<00:00,  5.14s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:48:56,033 WARNING synthesis text ڤان لەشکەران یەزدانێ براهیم ب زورێ ل دەوروبەرا خوە دانە قەبوول کرن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:48:57,363 INFO synthesis text ڤان لەشکەران یەزدانێ براهیم ب زورێ ل دەوروبەرا خوە دانە قەبوول کرن.
2026-10-13 08:49:00,970 INFO yield speech len 5.48, rtf 0.658341567881786
100%|██████████| 1/1 [00:04<00:00,  4.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:02,345 INFO synthesis text د ڤی ماوەی دا دەست ژ نڤێسینا هوزانێ بەر نادەت هەروەک ئەو ب خو دبێژیت: ئەڤە کارەکێ گەلەکێ بچووکە ئەز پێ ڕابوویم.
2026-10-13 08:49:07,410 INFO yield speech len 8.04, rtf 0.630024357221613
100%|██████████| 1/1 [00:06<00:00,  6.40s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:08,759 INFO synthesis text درێژ بوو، ئەڤە ب دلێ کچێت وێ نەبوو، وان پێ نەخوشبوو هەر ڕۆژ ل گەل دەنگێ دیکلی ژ خەو ڕابن.
2026-10-13 08:49:12,883 INFO yield speech len 6.36, rtf 0.6484755555038931
100%|██████████| 1/1 [00:05<00:00,  5.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:12,941 WARNING synthesis text سەروکێ حکومەتێ دێ کومەڵگەها پەروەردەیا بارزانیێ نەمر ڤەکەت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:49:14,267 INFO synthesis text سەروکێ حکومەتێ دێ کومەڵگەها پەروەردەیا بارزانیێ نەمر ڤەکەت.
2026-10-13 08:49:17,197 INFO yield speech len 4.36, rtf 0.6720050759271744
100%|██████████| 1/1 [00:04<00:00,  4.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:18,557 INFO synthesis text بمخابنیڤە؛ د ڤێ چالاکیێ دا پێشمەرگەیێ قارەمان سەید عەبدوڵا شەهید بوو، کو دبیتە ئێکەم شەهیدێ شوڕەشا گولانا پێشکەفتنخواز.
2026-10-13 08:49:24,041 INFO yield speech len 8.8, rtf 0.6231960383328524
100%|██████████| 1/1 [00:06<00:00,  6.81s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:25,412 INFO synthesis text بریکارێ کارێن لێڤاندوڤسکی هێرشبەرێ پولەندی یێ بەرشلونا ل دور نووچەیێن هێلانا وی هێرشبەری بۆ ڕێزێن یانەیا بەرشلونا هاتە دەنگ.
2026-10-13 08:49:30,583 INFO yield speech len 8.2, rtf 0.6306146993869689
100%|██████████| 1/1 [00:06<00:00,  6.51s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:30,631 WARNING synthesis text شینا کراسێ سور و شین. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:49:31,947 INFO synthesis text شینا کراسێ سور و شین.
2026-10-13 08:49:33,839 INFO yield speech len 2.52, rtf 0.7507970408787803
100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:35,179 INFO synthesis text دویماهیک پێشداچوونێن ڕەوشا ئالوز یا ڕۆژهەلاتا ناڤین و گرنگیا پاراستنا ئاساییش و سەقامگیریا دەڤەرێ، پشکەکا دی یا گوتوبێژان بوو.
2026-10-13 08:49:41,070 INFO yield speech len 9.48, rtf 0.6213872493067873
100%|██████████| 1/1 [00:07<00:00,  7.20s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:41,131 WARNING synthesis text سیپنوی قیزا میرەکی ژ میرێت میدیایە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:49:42,453 INFO synthesis text سیپنوی قیزا میرەکی ژ میرێت میدیایە.
2026-10-13 08:49:44,771 INFO yield speech len 3.24, rtf 0.7153628784933207
100%|██████████| 1/1 [00:03<00:00,  3.64s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:46,148 INFO synthesis text ئیرۆ جەژنا تەیە دایێ ژبیر نەکە د گەل نڤێژا خوە دوعایێ ژ خوەدێ بۆ من بکە.
2026-10-13 08:49:50,189 INFO yield speech len 6.16, rtf 0.6559604948217218
100%|██████████| 1/1 [00:05<00:00,  5.37s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:51,559 INFO synthesis text ژ دەستپێکا ژیانێ بوویە شاهدێ بویەرێن دیروکی و سەروکانیا چاڤکانی و زانینا ڕوپەلێن دیروکێ، مروڤ دروستکەرێ وێنەیە.
2026-10-13 08:49:56,942 INFO yield speech len 8.68, rtf 0.6201991287793982
100%|██████████| 1/1 [00:06<00:00,  6.71s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:49:58,346 INFO synthesis text ب هەر دوخەکێ هەبیت، هەستکرنا خوشیا ژ شعرێ دگەهیتە مە کێم، یان زور بۆ جوانیا فورمی دزڤریت.
2026-10-13 08:50:02,883 INFO yield speech len 7.04, rtf 0.6445108150893991
100%|██████████| 1/1 [00:05<00:00,  5.89s/it]

  abdullah: 75/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:04,280 INFO synthesis text دەما من دیت تە چەوا ناڤێ من یێ رەش کری دا تو بگەهیە پلەیەکێ، من زانی کا چ  کەرب و کینێن  ڤەشارتی د دلێ تە دا ھەنە.
2026-10-13 08:50:09,501 INFO yield speech len 8.24, rtf 0.6335914424322183
100%|██████████| 1/1 [00:06<00:00,  6.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:10,848 INFO synthesis text ئەز ب بێدەنگی یا ل بەرامبەر تە راوەستایم، بەس نە ژ بەر هندێ کو تشتەک نینە، بەلکو ژبەرکو ناخێ من یێ دکەلیت.
2026-10-13 08:50:15,408 INFO yield speech len 7.12, rtf 0.6404498989662427
100%|██████████| 1/1 [00:05<00:00,  5.87s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:16,754 INFO synthesis text پشتی من هەمی تشتێن خۆ فیدا کرین، تو بێ منەت د روویێ من دا دئاخڤی، وەک بێژی تە ئەز چ جاران نەدیتیمە.
2026-10-13 08:50:21,886 INFO yield speech len 8.12, rtf 0.6319903975049851
100%|██████████| 1/1 [00:06<00:00,  6.45s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:23,249 INFO synthesis text هندە یێ عێجزم حەز دکەم ب تنێ بچمە جهەکێ و نە تە و نە چ کەسا ب حەیات نەبینم.
2026-10-13 08:50:27,394 INFO yield speech len 6.36, rtf 0.6518418683945757
100%|██████████| 1/1 [00:05<00:00,  5.47s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:28,763 INFO synthesis text ب ڕاستی پسیارێ ژ خۆ دکەم، تو چاوا دشێی ھندە مروڤەکێ  دلرەق بی و پاشی وەسا خو نیشان بدەی کو تشتەک چێ نەبوویە؟
2026-10-13 08:50:34,226 INFO yield speech len 8.8, rtf 0.6207725947553461
100%|██████████| 1/1 [00:06<00:00,  6.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:35,572 INFO synthesis text ئەز گەلەک ژ پاشەڕوژا خو دترسم نەشێم بدرستی بخوم یان ڤەخوم، چونکی نە یا دیارە کا دێ چ چێبیت و چ هێتە رێکا من.
2026-10-13 08:50:40,805 INFO yield speech len 8.32, rtf 0.6289514211507944
100%|██████████| 1/1 [00:06<00:00,  6.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:42,192 INFO synthesis text دەما تە تێلەفۆن ل سەر من دائێخستی، من مۆبایلا خۆ کێشا و ل عەردی دا و من دڤیا جیهان هەمی وەک وێ موبایلێ تێک بچیت.
2026-10-13 08:50:47,493 INFO yield speech len 8.4, rtf 0.6310534761065528
100%|██████████| 1/1 [00:06<00:00,  6.63s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:48,858 INFO synthesis text تە خو دیت، ئەڤرۆ پشتی تە ب پێکەنین ڤە یاری ب هەستێن من کرین، من زانی کو جیهان چەندا بێ بەختە.
2026-10-13 08:50:53,390 INFO yield speech len 7.04, rtf 0.6437048654664647
100%|██████████| 1/1 [00:05<00:00,  5.86s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:50:54,763 INFO synthesis text ئەو درەوا تە ل بەرانبەر دایکا من کری، وەسا ئەز یێ سوتیم کو ئێدی چ باوەری د ناڤبەرا مە دا نەما.
2026-10-13 08:50:59,012 INFO yield speech len 6.56, rtf 0.647621074827706
100%|██████████| 1/1 [00:05<00:00,  5.58s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:00,356 INFO synthesis text خولی بسەرێ تە وەرە، ما تو چ جار پێڤە ناچی، ئەڤە سەد جارا تە ئەو خەلەتی دﻭﻭبارەکر و ھەر پێڤە نەچوویە.
2026-10-13 08:51:05,432 INFO yield speech len 8.0, rtf 0.6345890164375305
100%|██████████| 1/1 [00:06<00:00,  6.39s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:06,949 INFO synthesis text پشتی سالانە پارێ خۆ من کۆم کری و ب خەمساریا تە هەمی چووی، من دڤیا ڤی باژێری ل بەر چاڤێت تە بکەمە تاریستان.
2026-10-13 08:51:12,028 INFO yield speech len 8.12, rtf 0.6255000095649307
100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:13,446 INFO synthesis text تشتێ ژ ھەمیا ب ئێشتر ئەوە کو تو حەقێ من ددەیتە کەسەکێ دی،  ھەر دێ بێژی بھنا خو فرھە بکە، ما چ وژدان سەرێ تە دا نینە، مالا تە.
2026-10-13 08:51:19,441 INFO yield speech len 9.8, rtf 0.6116851981805295
100%|██████████| 1/1 [00:07<00:00,  7.36s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:19,474 WARNING synthesis text پەح، چ چیایەکێ بلندە و چ دیمەنەکێ  سەرسورمانە! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:51:20,782 INFO synthesis text پەح، چ چیایەکێ بلندە و چ دیمەنەکێ  سەرسورمانە!
2026-10-13 08:51:23,675 INFO yield speech len 4.28, rtf 0.6760473006239561
100%|██████████| 1/1 [00:04<00:00,  4.21s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:25,046 INFO synthesis text ھەی ماشائەاللە، ئەڤ کچکە چەند یا ژیر و بلیمەتە خو ئێک پرسیار شاش نەکریە!
2026-10-13 08:51:28,973 INFO yield speech len 6.12, rtf 0.6416322359072617
100%|██████████| 1/1 [00:05<00:00,  5.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:30,346 INFO synthesis text ئەحو، ئەڤە چ ھێزە تو پێ دشێی ڤی بەری ڕاکەی، کەس نەشیایە حەتا نوکە ڤی راکەت!
2026-10-13 08:51:34,504 INFO yield speech len 6.4, rtf 0.6495797261595726
100%|██████████| 1/1 [00:05<00:00,  5.49s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:34,541 WARNING synthesis text ئوخ، ئەڤ کانییا ئاڤێ چەند یا سار و خوشە د ڤی گەرمی دا! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:51:35,848 INFO synthesis text ئوخ، ئەڤ کانییا ئاڤێ چەند یا سار و خوشە د ڤی گەرمی دا!
2026-10-13 08:51:39,089 INFO yield speech len 4.92, rtf 0.6586567173159219
100%|██████████| 1/1 [00:04<00:00,  4.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:40,450 INFO synthesis text وەختێ شەڤەکێ ئەز سەحدکەمە فلمێن بترس، وێ شەڤێ هەمیێ نەشێم بنڤم هندی خەونێن نەخوش دبینم.
2026-10-13 08:51:44,621 INFO yield speech len 6.4, rtf 0.6517373770475388
100%|██████████| 1/1 [00:05<00:00,  5.49s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:45,963 INFO synthesis text ئاخ، ئەڤ باژێڕە چەند یێ مەزنە و بێ سەروبەر بوویە، من باوەرنەدکر دێ ھوسا لێ ھێت!
2026-10-13 08:51:49,995 INFO yield speech len 6.24, rtf 0.6462523188346472
100%|██████████| 1/1 [00:05<00:00,  5.35s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:50,047 WARNING synthesis text وەی، ما ئەڤە چەوا تو ژ وی روودانێ قورتال بووی! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:51:51,364 INFO synthesis text وەی، ما ئەڤە چەوا تو ژ وی روودانێ قورتال بووی!
2026-10-13 08:51:54,175 INFO yield speech len 4.12, rtf 0.6821830874507867
100%|██████████| 1/1 [00:04<00:00,  4.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:51:54,200 WARNING synthesis text پەح، ئەڤە چ تێشتەکا شاهانە و ب تامە، من تێشتەکا ھوسا ل چ جھا نەخارییە! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:51:55,541 INFO synthesis text پەح، ئەڤە چ تێشتەکا شاهانە و ب تامە، من تێشتەکا ھوسا ل چ جھا نەخارییە!
2026-10-13 08:51:59,308 INFO yield speech len 6.0, rtf 0.627926786740621
100%|██████████| 1/1 [00:05<00:00,  5.11s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:00,656 INFO synthesis text ھەی ماشائەاللە، ئەڤ مالە چەند یا ب ڕێکوپێک و جوانە، دیکورێ وێ ئەز مەندەھوش کرم!
2026-10-13 08:52:04,770 INFO yield speech len 6.32, rtf 0.651006268549569
100%|██████████| 1/1 [00:05<00:00,  5.43s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:04,801 WARNING synthesis text ئەحو، تە چەوا ئەڤ هەمی کارە ب تنێ ب دوماهی ئینان! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:52:06,153 INFO synthesis text ئەحو، تە چەوا ئەڤ هەمی کارە ب تنێ ب دوماهی ئینان!
2026-10-13 08:52:08,907 INFO yield speech len 4.0, rtf 0.6884541511535645
100%|██████████| 1/1 [00:04<00:00,  4.11s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:10,265 INFO synthesis text ئوخ، چەند یا خوشە مرۆڤ پشتی ماندیبوونەکا درێژ بگەهیتە ئارمانجا خۆ و تێر بھنا خۆ بدەت!
2026-10-13 08:52:14,540 INFO yield speech len 6.72, rtf 0.6361318131287893
100%|██████████| 1/1 [00:05<00:00,  5.60s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:15,915 INFO synthesis text ئاخ،  بۆ وی دەمێ چووی و نەزڤری، باوەرکە ھێشتا ئەز یێ مەندەھﻭشم ژ چونا تە!
2026-10-13 08:52:19,520 INFO yield speech len 5.52, rtf 0.6530518117158309
100%|██████████| 1/1 [00:04<00:00,  4.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:19,554 WARNING synthesis text پەح، ئەڤ تڕۆمبێلە چەند یا ب لەز و ب هێزە، دێ بێژی فیرارییە! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:52:20,868 INFO synthesis text پەح، ئەڤ تڕۆمبێلە چەند یا ب لەز و ب هێزە، دێ بێژی فیرارییە!
2026-10-13 08:52:23,822 INFO yield speech len 4.36, rtf 0.6775542683557633
100%|██████████| 1/1 [00:04<00:00,  4.27s/it]

  abdullah: 100/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:25,186 INFO synthesis text ھەی ماشائەاللە، ئەڤ زارۆکە چەند یێ ب رەوشت و زمان شرینە، ب کەسێ مالێ ڤە نەچویە!
2026-10-13 08:52:29,239 INFO yield speech len 6.44, rtf 0.629415682383946
100%|██████████| 1/1 [00:05<00:00,  5.37s/it]

  abdullah: 101/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:30,650 INFO synthesis text سەد ڕێسایێن بۆ تە دبنە هاریکار ل سەر موکمکرنا زانستێ نەحوێ و زانینا ئیعڕابێ.
2026-10-13 08:52:34,870 INFO yield speech len 6.48, rtf 0.6513116536317047
100%|██████████| 1/1 [00:05<00:00,  5.59s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:34,919 WARNING synthesis text سێسەد و نوت و هەشت ڕۆژە قەوارێ زایونی جینوسایدا گەلێ فەلەستین دکەت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:52:36,270 INFO synthesis text سێسەد و نوت و هەشت ڕۆژە قەوارێ زایونی جینوسایدا گەلێ فەلەستین دکەت.
2026-10-13 08:52:40,057 INFO yield speech len 5.72, rtf 0.662092812411435
100%|██████████| 1/1 [00:05<00:00,  5.16s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:41,471 INFO synthesis text پارێزگارێ دهوکێ سەرا بارەگایێ لقا هەژدە دا و کومبوونەک د گەل ماموستایێن ڕاهێنەرێن ڤەکرنا خولێن ڕەوشەنبیری ئەنجام دا.
2026-10-13 08:52:46,884 INFO yield speech len 8.64, rtf 0.626554505692588
100%|██████████| 1/1 [00:06<00:00,  6.78s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:46,941 WARNING synthesis text ئەرێ تۆ باوەر دکەی، کو ڕوح ل گەل لەشی نامریت؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:52:48,294 INFO synthesis text ئەرێ تۆ باوەر دکەی، کو ڕوح ل گەل لەشی نامریت؟
2026-10-13 08:52:50,941 INFO yield speech len 3.84, rtf 0.6891772771875064
100%|██████████| 1/1 [00:04<00:00,  4.00s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:50,975 WARNING synthesis text بەلێ ژمارەکا شەڕکەرا دێ ل دویڤ من ڕا هێن، داکو موتەسەرفی بگرین. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:52:52,316 INFO synthesis text بەلێ ژمارەکا شەڕکەرا دێ ل دویڤ من ڕا هێن، داکو موتەسەرفی بگرین.
2026-10-13 08:52:55,598 INFO yield speech len 4.92, rtf 0.6670516680895797
100%|██████████| 1/1 [00:04<00:00,  4.63s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:55,641 WARNING synthesis text تە نەگوت ئەڤە چ پویچاتینە تو دکەی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:52:56,989 INFO synthesis text تە نەگوت ئەڤە چ پویچاتینە تو دکەی؟
2026-10-13 08:52:58,956 INFO yield speech len 2.6, rtf 0.7564313595111554
100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:52:58,986 WARNING synthesis text ب قەنجیێ گازندەیان ژ برایێ خوە بکە، ب خێرکرنێ بەرسڤا خرابیا وی بدە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:53:00,349 INFO synthesis text ب قەنجیێ گازندەیان ژ برایێ خوە بکە، ب خێرکرنێ بەرسڤا خرابیا وی بدە.
2026-10-13 08:53:04,156 INFO yield speech len 5.8, rtf 0.6563545095509496
100%|██████████| 1/1 [00:05<00:00,  5.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:05,563 INFO synthesis text دیجیتاڵ میدیا سپێدە: ئەڤرۆ شاندەکێ یەکگرتووی ئیسلامی کوردستان ل باژێرێ هەولێر سەرەدانا بزاڤا دیموکراتا ئاشوری کر.
2026-10-13 08:53:10,916 INFO yield speech len 8.6, rtf 0.6224050909973855
100%|██████████| 1/1 [00:06<00:00,  6.73s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:12,290 INFO synthesis text د کومبوونێ دا پەرەپێدانا پەیوەندیێن دوو لایەنە و بزاڤێن رویبرویبوونا کوچکرنا نەیاسایی گوتوبێژ کرن.
2026-10-13 08:53:16,479 INFO yield speech len 6.4, rtf 0.6546170637011528
100%|██████████| 1/1 [00:05<00:00,  5.53s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:16,525 WARNING synthesis text دروستکرنا پرەکا پیادە ل سەر ڕێکا دهوک - ئامێدیێ ل سەر ڕێکا بێسرێ. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:53:17,875 INFO synthesis text دروستکرنا پرەکا پیادە ل سەر ڕێکا دهوک - ئامێدیێ ل سەر ڕێکا بێسرێ.
2026-10-13 08:53:21,171 INFO yield speech len 4.92, rtf 0.669982811299766
100%|██████████| 1/1 [00:04<00:00,  4.65s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:22,570 INFO synthesis text ئەرێ حکومەتا فیدرال دێ پابەند بیت ب ڤەگوهاستنا شایستەیێن هەرێمێ ب پێی پشکا دیارکری د بودجەیا گشتی دا؟
2026-10-13 08:53:27,610 INFO yield speech len 7.92, rtf 0.6364337422631003
100%|██████████| 1/1 [00:06<00:00,  6.40s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:28,982 INFO synthesis text ئەرێ حەدیسەک هەیە بێژیت هەر کەسێ چل حەدیسان ژبەر کەت ڕوژا قیامەتێ دێ ل ڕێزا زانایان هێت؟
2026-10-13 08:53:33,731 INFO yield speech len 7.2, rtf 0.6596787108315362
100%|██████████| 1/1 [00:06<00:00,  6.09s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:33,765 WARNING synthesis text ئەرێ حوکمێ بانگی چیە، واجبە یان سونەتە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:53:35,104 INFO synthesis text ئەرێ حوکمێ بانگی چیە، واجبە یان سونەتە؟
2026-10-13 08:53:37,554 INFO yield speech len 3.48, rtf 0.7041862641257801
100%|██████████| 1/1 [00:03<00:00,  3.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:38,952 INFO synthesis text ئەرێ حوکمێ بەرێخودانا ب مەخسەد ژ زەلامی چیە بۆ ژنکەکا بیانی یان بۆ ژنا وی ب خو؟
2026-10-13 08:53:43,122 INFO yield speech len 6.4, rtf 0.6515669077634811
100%|██████████| 1/1 [00:05<00:00,  5.54s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:44,496 INFO synthesis text ئەرێ حوکمێ خواندنا قورئانێ ل مزگەفتان شەڤا ئەینی و ڕوژا ئەینی بەری خوتبێ چیە؟
2026-10-13 08:53:48,461 INFO yield speech len 6.16, rtf 0.6437561341694423
100%|██████████| 1/1 [00:05<00:00,  5.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:48,500 WARNING synthesis text وەی، ما ئەڤە چەوا تو ژ وی روودانێ قورتال بووی! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:53:49,870 INFO synthesis text وەی، ما ئەڤە چەوا تو ژ وی روودانێ قورتال بووی!
2026-10-13 08:53:52,423 INFO yield speech len 3.52, rtf 0.725282525474375
100%|██████████| 1/1 [00:03<00:00,  3.93s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:52,457 WARNING synthesis text ئەرێ حوکمێ موسیقێ چیە، حەلالە یان حەرامە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:53:53,799 INFO synthesis text ئەرێ حوکمێ موسیقێ چیە، حەلالە یان حەرامە؟
2026-10-13 08:53:56,291 INFO yield speech len 3.48, rtf 0.7160163473808903
100%|██████████| 1/1 [00:03<00:00,  3.84s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:53:56,339 WARNING synthesis text ئەرێ حوکمێ نڤێژا ب جەماعەت چیە، سونەتە یان واجبە، و دەلیل و بەلگە چیە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:53:57,697 INFO synthesis text ئەرێ حوکمێ نڤێژا ب جەماعەت چیە، سونەتە یان واجبە، و دەلیل و بەلگە چیە؟
2026-10-13 08:54:01,220 INFO yield speech len 5.24, rtf 0.6722957123326891
100%|██████████| 1/1 [00:04<00:00,  4.89s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:02,606 INFO synthesis text ئەرێ خەلکێ ئاکرێ پتر ژ کیژ دەڤەرەکا دیتر پتر ئاشنایی د گەل کوردی و خواندنا کوردی هەبوو.
2026-10-13 08:54:07,235 INFO yield speech len 7.24, rtf 0.6392556659424502
100%|██████████| 1/1 [00:05<00:00,  5.98s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:07,289 WARNING synthesis text ئەرێ خودانکرنا سێویێ دایکا وی مری ب خێرترە یان خودانکرنا ئێتیمی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:54:08,653 INFO synthesis text ئەرێ خودانکرنا سێویێ دایکا وی مری ب خێرترە یان خودانکرنا ئێتیمی؟
2026-10-13 08:54:11,943 INFO yield speech len 4.92, rtf 0.6686858529967021
100%|██████████| 1/1 [00:04<00:00,  4.66s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:11,974 WARNING synthesis text ئەرێ خوشەڤیا من گەنجە زەلامەک ئازا و مێرخاس  پا درۆڤ چ لێ هات؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:54:13,314 INFO synthesis text ئەرێ خوشەڤیا من گەنجە زەلامەک ئازا و مێرخاس  پا درۆڤ چ لێ هات؟
2026-10-13 08:54:16,953 INFO yield speech len 5.56, rtf 0.6544437768647997
100%|██████████| 1/1 [00:04<00:00,  4.98s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:18,348 INFO synthesis text ئەرێ خوێنەر لێرە ناپرسیت، ئەرێ چ جیاوازی د ناڤبەرا گولێن هەلبەستێ ئاماژە پێ کری و مروڤێن ڕاستگۆ دا هەیە؟
2026-10-13 08:54:22,964 INFO yield speech len 7.28, rtf 0.6340110367471045
100%|██████████| 1/1 [00:05<00:00,  5.98s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:24,365 INFO synthesis text ئەرێ خو گرێدان ب هندەک بیروباوەران ڤە، پاشڤەمان و کەڤنەپەرستیە و شانازی ب بەرەلاییێ یان عەشیرەتگەریێ (مودێرنیزمە)؟
2026-10-13 08:54:30,031 INFO yield speech len 9.0, rtf 0.6295949353112115
100%|██████████| 1/1 [00:07<00:00,  7.04s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:31,402 INFO synthesis text ئەرێ د دیروکا ئیسلامێ دا دەولەت ب بەلاڤکرنا زەکاتێ ڕابوویە، و تە چ ئاخفتن ل سەر ڤێ چەندێ هەیە؟
2026-10-13 08:54:35,834 INFO yield speech len 6.88, rtf 0.644185931183571
100%|██████████| 1/1 [00:05<00:00,  5.78s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:37,223 INFO synthesis text ئەرێ دانوستاندنەک یان بزاڤەک هەیە بۆ سەر ژ نوی دەستپێکرنا پێڤاژۆیا ئاشتیێ ل ترکیا و چارەسەرکرنا پرسا کوردی؟
2026-10-13 08:54:42,472 INFO yield speech len 8.36, rtf 0.6278340611161228
100%|██████████| 1/1 [00:06<00:00,  6.61s/it]

  hayfa: 25/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:43,954 INFO synthesis text ئەرێ دەستنڤێژ بۆ سوجدا تیلاوێ مەرجە، ئانکو دڤێت مروڤێ ب دەستنڤێژ بیت هەتا بۆ هەبیت بچیتە سوجدا تیلاوێ؟
2026-10-13 08:54:49,219 INFO yield speech len 8.28, rtf 0.6358535969314945
100%|██████████| 1/1 [00:06<00:00,  6.64s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:49,254 WARNING synthesis text پەح، ئەڤە چ تێشتەکا شاهانە و ب تامە، من تێشتەکا ھوسا ل چ جھا نەخارییە! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:54:50,591 INFO synthesis text پەح، ئەڤە چ تێشتەکا شاهانە و ب تامە، من تێشتەکا ھوسا ل چ جھا نەخارییە!
2026-10-13 08:54:54,387 INFO yield speech len 5.68, rtf 0.6682858080931113
100%|██████████| 1/1 [00:05<00:00,  5.14s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:54:55,787 INFO synthesis text ئەرێ دەمێ زکرێ سپێدێ و ئێڤاریان یێ ئاشکرا و تخویب دایە یان یێ ڤەکریە و هەر وەختێ مروڤ بکەت دورستە؟
2026-10-13 08:55:00,623 INFO yield speech len 7.64, rtf 0.6329584496183546
100%|██████████| 1/1 [00:06<00:00,  6.19s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:02,017 INFO synthesis text ئەرێ دورستە ئەز سوجدا تیلاوێ گیرو کەم هەتا پەرێ خو دبەمە دویماهیێ یان دگەهمە دویماهیا ویردا خو؟
2026-10-13 08:55:06,605 INFO yield speech len 7.12, rtf 0.6444109289833668
100%|██████████| 1/1 [00:05<00:00,  5.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:08,043 INFO synthesis text ئەرێ دورستە حەج پێش نەساخەکێ ئاسایی ڤە بێتە کرن، یان ژی زیندانیەکێ زیندانیا وی یا درێژ؟
2026-10-13 08:55:12,688 INFO yield speech len 7.32, rtf 0.63451824943876
100%|██████████| 1/1 [00:06<00:00,  6.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:12,737 WARNING synthesis text ئەرێ دورستە دەوات د ڕەمەزانێ دا بێتە کرن؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:55:14,084 INFO synthesis text ئەرێ دورستە دەوات د ڕەمەزانێ دا بێتە کرن؟
2026-10-13 08:55:16,167 INFO yield speech len 2.84, rtf 0.7336258888244629
100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:17,563 INFO synthesis text ئەرێ دورستە ژن سەرشویشتنا خو گیرو بکەت و ب جەنابەت بنڤیت پاشی هەر دەمێ ڕابوو سەرێ خو بشوت؟
2026-10-13 08:55:21,626 INFO yield speech len 6.24, rtf 0.6511372251388354
100%|██████████| 1/1 [00:05<00:00,  5.43s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:21,662 WARNING synthesis text ئەرێ دورستە ژن سەرێ ژنێ بشوت و چو جلک ل بەر نەبن؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:55:23,006 INFO synthesis text ئەرێ دورستە ژن سەرێ ژنێ بشوت و چو جلک ل بەر نەبن؟
2026-10-13 08:55:26,048 INFO yield speech len 4.44, rtf 0.6851294556179561
100%|██████████| 1/1 [00:04<00:00,  4.39s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:26,084 WARNING synthesis text ئەرێ دورستە مروڤ تەراویحان نەکەت و نڤێژێت شەڤێ بکەت؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:55:27,449 INFO synthesis text ئەرێ دورستە مروڤ تەراویحان نەکەت و نڤێژێت شەڤێ بکەت؟
2026-10-13 08:55:30,523 INFO yield speech len 4.6, rtf 0.6682233188463295
100%|██████████| 1/1 [00:04<00:00,  4.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:31,898 INFO synthesis text ھەی ماشائەاللە، ئەڤ مالە چەند یا ب ڕێکوپێک و جوانە، دیکورێ وێ ئەز مەندەھوش کرم!
2026-10-13 08:55:35,940 INFO yield speech len 6.16, rtf 0.656090115571951
100%|██████████| 1/1 [00:05<00:00,  5.39s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:37,317 INFO synthesis text ئەرێ دورستە مروڤ سونەتان بکەت بەلێ چ ناڤان لێ نەئینیت و بەس بێژیت: من ئنیەتە دوو ڕکاعەت سونەت بکەم؟
2026-10-13 08:55:41,783 INFO yield speech len 7.0, rtf 0.6380876473018101
100%|██████████| 1/1 [00:05<00:00,  5.82s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:43,182 INFO synthesis text ئەرێ دورستە نڤێژا ئێڤاری د گەل خوتبێ بێتە جەمعکرن، هەکە مروڤ ل سەر سەفەرێ بیت، هندەک دبێژن: ئەڤە نابیت.
2026-10-13 08:55:47,794 INFO yield speech len 7.24, rtf 0.637051150285078
100%|██████████| 1/1 [00:05<00:00,  5.97s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:47,841 WARNING synthesis text ئەرێ دورستە نڤێژێت سونەت ب جەماعەت بێنە کرن ژبلی تەراویح و ویتران؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:55:49,189 INFO synthesis text ئەرێ دورستە نڤێژێت سونەت ب جەماعەت بێنە کرن ژبلی تەراویح و ویتران؟
2026-10-13 08:55:53,009 INFO yield speech len 5.8, rtf 0.658642053604126
100%|██████████| 1/1 [00:05<00:00,  5.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:53,047 WARNING synthesis text ئەرێ دینداریا تە؛ تە پال ددەت د ڕێکا ڤان گونەهان دا ڕاوەستی ئان نە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:55:54,395 INFO synthesis text ئەرێ دینداریا تە؛ تە پال ددەت د ڕێکا ڤان گونەهان دا ڕاوەستی ئان نە؟
2026-10-13 08:55:57,786 INFO yield speech len 5.0, rtf 0.6781929492950439
100%|██████████| 1/1 [00:04<00:00,  4.74s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:55:57,830 WARNING synthesis text ئەرێ دێ بیتە ڕاپورت یان بۆ هونەرەکی دیێ ڕوژنامەڤانیێ باشترە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:55:59,181 INFO synthesis text ئەرێ دێ بیتە ڕاپورت یان بۆ هونەرەکی دیێ ڕوژنامەڤانیێ باشترە؟
2026-10-13 08:56:02,585 INFO yield speech len 5.12, rtf 0.6648441310971975
100%|██████████| 1/1 [00:04<00:00,  4.76s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:02,630 WARNING synthesis text ئەرێ زکرێ د ناڤبەرا تەراویحان دا تشتەک بۆ هەیە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:03,979 INFO synthesis text ئەرێ زکرێ د ناڤبەرا تەراویحان دا تشتەک بۆ هەیە؟
2026-10-13 08:56:06,555 INFO yield speech len 3.68, rtf 0.7000822087992792
100%|██████████| 1/1 [00:03<00:00,  3.93s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:06,590 WARNING synthesis text ئەرێ ڕاتیبا خوتبێ چاوایە و ڕاتیبە هەیە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:07,949 INFO synthesis text ئەرێ ڕاتیبا خوتبێ چاوایە و ڕاتیبە هەیە؟
2026-10-13 08:56:10,284 INFO yield speech len 3.24, rtf 0.7205542958812948
100%|██████████| 1/1 [00:03<00:00,  3.70s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:11,677 INFO synthesis text ئەرێ ڕاستە ئیزایا گوری نینە و چ بەلگە ژ قورئانێ ل سەر نینن هەر وەکی عەلی مەنصور کەیالی دبێژیت؟
2026-10-13 08:56:16,262 INFO yield speech len 7.0, rtf 0.6549365520477295
100%|██████████| 1/1 [00:05<00:00,  5.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:17,667 INFO synthesis text ئەرێ ڕاستە گەلەک جەژن وعیدێن دن هەنە، زێدەباری تەوافان کو وەکو جەژنێن هەریمی تێنە هژمارتن.
2026-10-13 08:56:22,424 INFO yield speech len 7.4, rtf 0.6428829721502355
100%|██████████| 1/1 [00:06<00:00,  6.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:22,459 WARNING synthesis text ئەحو، تە چەوا ئەڤ هەمی کارە ب تنێ ب دوماهی ئینان! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:23,797 INFO synthesis text ئەحو، تە چەوا ئەڤ هەمی کارە ب تنێ ب دوماهی ئینان!
2026-10-13 08:56:26,540 INFO yield speech len 3.96, rtf 0.6926535957991475
100%|██████████| 1/1 [00:04<00:00,  4.09s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:26,571 WARNING synthesis text ئەرێ ڕاستە نڤێژا ل چولی ب خێرترە ژ نڤێژا ل مال و ل مزگەفتێ؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:27,907 INFO synthesis text ئەرێ ڕاستە نڤێژا ل چولی ب خێرترە ژ نڤێژا ل مال و ل مزگەفتێ؟
2026-10-13 08:56:31,083 INFO yield speech len 4.8, rtf 0.6615879138310751
100%|██████████| 1/1 [00:04<00:00,  4.52s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:32,472 INFO synthesis text ئەرێ ژبەر هندێ بوو، ئەڤرۆکە گرنگترین ڕوژە دژیانا وی دا، ئەو ڕوژە یا مروڤ دنیایێ دهێلیت.
2026-10-13 08:56:36,674 INFO yield speech len 6.48, rtf 0.6485771985701573
100%|██████████| 1/1 [00:05<00:00,  5.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:36,728 WARNING synthesis text ئەرێ سەججادی د گەل وێ چەندێ بوویە خەلکێ دەڤەرێ ب شێوەزارێ خوە بخوینن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:38,086 INFO synthesis text ئەرێ سەججادی د گەل وێ چەندێ بوویە خەلکێ دەڤەرێ ب شێوەزارێ خوە بخوینن.
2026-10-13 08:56:41,796 INFO yield speech len 5.64, rtf 0.6577849810850536
100%|██████████| 1/1 [00:05<00:00,  5.07s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:41,860 WARNING synthesis text ئەرێ سەرشویشتنا خوتبێ د دەرحەقێ ژنێ دا ژی سونەتە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:43,219 INFO synthesis text ئەرێ سەرشویشتنا خوتبێ د دەرحەقێ ژنێ دا ژی سونەتە؟
2026-10-13 08:56:46,134 INFO yield speech len 4.44, rtf 0.6565703465057923
100%|██████████| 1/1 [00:04<00:00,  4.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:46,169 WARNING synthesis text ئەرێ سەیدا، ئەڤ مروڤە ب مرنەکا سروشتی مریە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:56:47,513 INFO synthesis text ئەرێ سەیدا، ئەڤ مروڤە ب مرنەکا سروشتی مریە؟
2026-10-13 08:56:49,824 INFO yield speech len 3.24, rtf 0.7132937142878403
100%|██████████| 1/1 [00:03<00:00,  3.66s/it]

  hayfa: 50/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:51,269 INFO synthesis text ئەرێ سوجدا شوکرێ حوکمێ وێ چیە و دەستنڤێژ بۆ مەرجە و دڤێت بەرێ مروڤی ل قیبلێ بیت؟
2026-10-13 08:56:55,735 INFO yield speech len 7.04, rtf 0.6344735622406006
100%|██████████| 1/1 [00:05<00:00,  5.84s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:56:57,109 INFO synthesis text ئەرێ شارستانیەتێ جهێ عەشیرەتگیریێ و خو حلیکرن بۆ ئاغا و بەرپرسا گرتیە و خایین و تۆمەتبارێن کریارێن ئەنفالا کێشاینە دادگەهێ!
2026-10-13 08:57:03,086 INFO yield speech len 10.0, rtf 0.5977492570877075
100%|██████████| 1/1 [00:07<00:00,  7.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:03,133 WARNING synthesis text ئەرێ عائیشایێ شیرێ سنگێ خو ددا زەلامەکی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:57:04,485 INFO synthesis text ئەرێ عائیشایێ شیرێ سنگێ خو ددا زەلامەکی؟
2026-10-13 08:57:06,896 INFO yield speech len 3.36, rtf 0.7175123407727196
100%|██████████| 1/1 [00:03<00:00,  3.77s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:08,283 INFO synthesis text ئەرێ غوسلا ژنێ ب تەیەمومێ ڕادبیت یان نە، و تەیمومێ بۆ جەنابەتێ چاوا دکەن؟
2026-10-13 08:57:12,185 INFO yield speech len 6.0, rtf 0.650197426478068
100%|██████████| 1/1 [00:05<00:00,  5.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:12,228 WARNING synthesis text ئەرێ فەراتیا زەکاتێ ل کیرێ دیار دبیت و چ جهێ خو د ئیسلامێ دا هەیە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:57:13,575 INFO synthesis text ئەرێ فەراتیا زەکاتێ ل کیرێ دیار دبیت و چ جهێ خو د ئیسلامێ دا هەیە؟
2026-10-13 08:57:17,089 INFO yield speech len 5.36, rtf 0.6555704038534591
100%|██████████| 1/1 [00:04<00:00,  4.87s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:17,137 WARNING synthesis text ئەرێ قامەت بۆ هەمی نڤێژێت ب جەماعەت دهێنە کرن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:57:18,493 INFO synthesis text ئەرێ قامەت بۆ هەمی نڤێژێت ب جەماعەت دهێنە کرن.
2026-10-13 08:57:21,075 INFO yield speech len 3.8, rtf 0.6795731343721089
100%|██████████| 1/1 [00:03<00:00,  3.94s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:21,119 WARNING synthesis text ئەرێ کاروبارێت جڤاکی و کومەلاتیێ چ گرنگیا خو هەیە د ئیسلامێ  دا؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:57:22,469 INFO synthesis text ئەرێ کاروبارێت جڤاکی و کومەلاتیێ چ گرنگیا خو هەیە د ئیسلامێ  دا؟
2026-10-13 08:57:25,794 INFO yield speech len 5.08, rtf 0.6545927111558089
100%|██████████| 1/1 [00:04<00:00,  4.68s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:27,197 INFO synthesis text ئەرێ کچێ ماف هەیە حەزکرنا خو ب ڕێکەکێ بۆ کورەکێ باش و موسلمان دیار کەت شوی پێ بکەت دا بخوازیت؟
2026-10-13 08:57:31,593 INFO yield speech len 6.96, rtf 0.6317251372611385
100%|██████████| 1/1 [00:05<00:00,  5.75s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:33,011 INFO synthesis text ئەرێ کەیسێن چەند کرێکاران ل دادگەهان هاتینە ئێکلاکرن و مافێن وان هاتینە ستاندن؟
2026-10-13 08:57:37,285 INFO yield speech len 6.64, rtf 0.643721258783915
100%|██████████| 1/1 [00:05<00:00,  5.63s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:37,333 WARNING synthesis text ئەرێ کورد ب رێ ڤە دهێن بۆ نک مە ڤە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:57:38,685 INFO synthesis text ئەرێ کورد ب رێ ڤە دهێن بۆ نک مە ڤە؟
2026-10-13 08:57:40,495 INFO yield speech len 2.4, rtf 0.7542667786280315
100%|██████████| 1/1 [00:03<00:00,  3.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:40,541 WARNING synthesis text ئەرێ گەلۆ: ئەڤێت مە برێزکرین یەک تشتن، یان ژ هەڤ دجودانە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:57:41,894 INFO synthesis text ئەرێ گەلۆ: ئەڤێت مە برێزکرین یەک تشتن، یان ژ هەڤ دجودانە؟
2026-10-13 08:57:45,327 INFO yield speech len 5.16, rtf 0.6654918193817139
100%|██████████| 1/1 [00:04<00:00,  4.79s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:46,777 INFO synthesis text ئەرێ ل سەر ژنێ ئەرکە ئەو خزمەتا زەلامێ خو و مالا وی بکەت و ما هەکە نەکر یا گونەهکارە؟
2026-10-13 08:57:51,132 INFO yield speech len 6.84, rtf 0.636695490943061
100%|██████████| 1/1 [00:05<00:00,  5.72s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:52,492 INFO synthesis text ئاخ،  بۆ وی دەمێ چووی و نەزڤری، باوەرکە ھێشتا ئەز یێ مەندەھﻭشم ژ چونا تە!
2026-10-13 08:57:56,186 INFO yield speech len 5.64, rtf 0.6550003873541
100%|██████████| 1/1 [00:05<00:00,  5.03s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:57:57,598 INFO synthesis text ئەرێ ل کیژ مزگەفتێ ب خێرترە، مروڤ نڤێژا خو یا جەماعەت تێڤە بکەت، یان ژی هەمی وەکی ئێکن؟
2026-10-13 08:58:01,678 INFO yield speech len 6.44, rtf 0.6336100353217272
100%|██████████| 1/1 [00:05<00:00,  5.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:01,734 WARNING synthesis text ئەرێ ما بوچی مروڤ بترسیت؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:03,085 INFO synthesis text ئەرێ ما بوچی مروڤ بترسیت؟
2026-10-13 08:58:04,758 INFO yield speech len 2.2, rtf 0.7602915980599143
100%|██████████| 1/1 [00:03<00:00,  3.03s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:04,785 WARNING synthesis text ئەرێ ما تو ژ دایکا مە باوەردارا عائیشایێ باشتری؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:06,151 INFO synthesis text ئەرێ ما تو ژ دایکا مە باوەردارا عائیشایێ باشتری؟
2026-10-13 08:58:08,674 INFO yield speech len 3.68, rtf 0.6854628739149674
100%|██████████| 1/1 [00:03<00:00,  3.89s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:08,718 WARNING synthesis text ئەرێ ما دێ حەژێکرنا دنیایێ سەرەدانا  گۆڕا پێغەمبەرێ خو سلاڤ لێ بن هێلی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:10,070 INFO synthesis text ئەرێ ما دێ حەژێکرنا دنیایێ سەرەدانا  گۆڕا پێغەمبەرێ خو سلاڤ لێ بن هێلی؟
2026-10-13 08:58:13,892 INFO yield speech len 5.96, rtf 0.6412610111620602
100%|██████████| 1/1 [00:05<00:00,  5.18s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:15,287 INFO synthesis text ئەرێ ما گەنجێ مەژی نە بەشەکە ژ سیاسەتا کوردی یا بەرێ وی دایە توندرەوی و تولڤەکرنێ؟
2026-10-13 08:58:19,333 INFO yield speech len 6.24, rtf 0.6484784759007968
100%|██████████| 1/1 [00:05<00:00,  5.40s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:19,367 WARNING synthesis text ئەرێ ما من نەگوتییە تە نەزڤڕیە ڤێرێ جارەکا دی؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:20,711 INFO synthesis text ئەرێ ما من نەگوتییە تە نەزڤڕیە ڤێرێ جارەکا دی؟
2026-10-13 08:58:23,104 INFO yield speech len 3.4, rtf 0.7039082751554602
100%|██████████| 1/1 [00:03<00:00,  3.74s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:23,140 WARNING synthesis text ئەرێ ما نە بەسی هندێ یە مە ب خو وانەک ژ ڤێ دنیایا  فرەه وەرگڕتبا! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:24,481 INFO synthesis text ئەرێ ما نە بەسی هندێ یە مە ب خو وانەک ژ ڤێ دنیایا  فرەه وەرگڕتبا!
2026-10-13 08:58:27,483 INFO yield speech len 4.48, rtf 0.6700284779071807
100%|██████████| 1/1 [00:04<00:00,  4.35s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:28,887 INFO synthesis text ئەرێ ما وان نەزانیە، خودێ نهینی و پستەپستا وان دزانیت، و ب ڕاستی خودێ زێدە زانایێ نهینیانە.
2026-10-13 08:58:33,254 INFO yield speech len 7.04, rtf 0.6202707575126127
100%|██████████| 1/1 [00:05<00:00,  5.74s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:34,653 INFO synthesis text ئەرێ مافەک ژ مافێن کوردستانێ ژ هەلدانەڤا ڤان بەرپەران دەستڤە دهێت یان ئەوێن هەیی ژی ژ دەست دچن.
2026-10-13 08:58:39,390 INFO yield speech len 7.52, rtf 0.6298942134735432
100%|██████████| 1/1 [00:06<00:00,  6.10s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:39,435 WARNING synthesis text ئەرێ مروڤ فتارا خو بەری ل سەر چ بکەت ب خێرترە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:40,803 INFO synthesis text ئەرێ مروڤ فتارا خو بەری ل سەر چ بکەت ب خێرترە؟
2026-10-13 08:58:43,233 INFO yield speech len 3.52, rtf 0.690490413795818
100%|██████████| 1/1 [00:03<00:00,  3.80s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:44,615 INFO synthesis text ئەرێ مروڤێ ئازادە ل نیڤا سویکێ دەنگێ ژ هەمیان بلندتر بدەتە ڕادیۆیا خو و پویتە ب کەسێ نەکەت!
2026-10-13 08:58:49,243 INFO yield speech len 7.52, rtf 0.6153914522617422
100%|██████████| 1/1 [00:05<00:00,  5.99s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:49,275 WARNING synthesis text ئەرێ مروڤێ ب جەنابەت چ ژن چ مێر دشێت زکر و دوعایان بکەت؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:58:50,626 INFO synthesis text ئەرێ مروڤێ ب جەنابەت چ ژن چ مێر دشێت زکر و دوعایان بکەت؟
2026-10-13 08:58:53,653 INFO yield speech len 4.64, rtf 0.6525826351395969
100%|██████████| 1/1 [00:04<00:00,  4.38s/it]

  hayfa: 75/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:55,081 INFO synthesis text ئەرێ مەبەستا وی ئەوە کو هێزێن وی ل چیایێن قەندیلی نە ل باشووری کوردستانێ؟
2026-10-13 08:58:58,939 INFO yield speech len 6.08, rtf 0.6346255932983599
100%|██████████| 1/1 [00:05<00:00,  5.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:58:58,971 WARNING synthesis text ئەرێ موسلمانە یێ گوهداریا پێغەمبەری سلاڤێت خودێ ل سەر بن نەکەت؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:00,320 INFO synthesis text ئەرێ موسلمانە یێ گوهداریا پێغەمبەری سلاڤێت خودێ ل سەر بن نەکەت؟
2026-10-13 08:59:03,162 INFO yield speech len 4.28, rtf 0.6640959008831844
100%|██████████| 1/1 [00:04<00:00,  4.20s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:04,578 INFO synthesis text ئەرێ میدیایا مە ل دەڤەرا بەهدینان بوویە میدیایەکا پیشەیی، مۆدێرن و سەردەم؟
2026-10-13 08:59:08,169 INFO yield speech len 5.52, rtf 0.650473738062209
100%|██████████| 1/1 [00:04<00:00,  4.97s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:08,216 WARNING synthesis text ئەرێ نڤێژ د دێران ڤە دئێتە کرن، ئانکو: دورستە نڤێژ د دێران ڤە بێتە کرن؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:09,571 INFO synthesis text ئەرێ نڤێژ د دێران ڤە دئێتە کرن، ئانکو: دورستە نڤێژ د دێران ڤە بێتە کرن؟
2026-10-13 08:59:13,039 INFO yield speech len 5.24, rtf 0.6618521595729217
100%|██████████| 1/1 [00:04<00:00,  4.83s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:13,075 WARNING synthesis text ئەرێ نڤێژێت سونەت کیژک ژهەمیان ب خێرترن و جوداهی د ناڤبەرا وان دا هەیە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:14,417 INFO synthesis text ئەرێ نڤێژێت سونەت کیژک ژهەمیان ب خێرترن و جوداهی د ناڤبەرا وان دا هەیە؟
2026-10-13 08:59:18,166 INFO yield speech len 5.68, rtf 0.6600368610570129
100%|██████████| 1/1 [00:05<00:00,  5.10s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:19,569 INFO synthesis text ئەرێ هەر سۆرەتا مروڤی د نڤێژێ دا خواند دڤێت دەستپێکا وێ تەعەووز و بەسمەلێ بکەین؟
2026-10-13 08:59:23,428 INFO yield speech len 5.76, rtf 0.6698492914438248
100%|██████████| 1/1 [00:05<00:00,  5.23s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:24,799 INFO synthesis text ئەرێ هەر گاڤا مروڤی ڤیا دەستنڤێژا خو بشوت دڤێت بچیتە تارەتێ، خو هەکە یێ پێدڤی ژی نەبیت؟
2026-10-13 08:59:28,900 INFO yield speech len 6.4, rtf 0.6406976655125618
100%|██████████| 1/1 [00:05<00:00,  5.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:28,943 WARNING synthesis text پەح، ئەڤ تڕۆمبێلە چەند یا ب لەز و ب هێزە، دێ بێژی فیرارییە! too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:30,300 INFO synthesis text پەح، ئەڤ تڕۆمبێلە چەند یا ب لەز و ب هێزە، دێ بێژی فیرارییە!
2026-10-13 08:59:33,438 INFO yield speech len 4.8, rtf 0.6537419060866039
100%|██████████| 1/1 [00:04<00:00,  4.50s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:33,476 WARNING synthesis text ئەرێ هەکە ژنتیێت ئێک خویشکێت ئێک بن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:34,823 INFO synthesis text ئەرێ هەکە ژنتیێت ئێک خویشکێت ئێک بن.
2026-10-13 08:59:37,040 INFO yield speech len 3.08, rtf 0.7197452830029772
100%|██████████| 1/1 [00:03<00:00,  3.57s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:37,072 WARNING synthesis text ئەرێ هوین دکەیفخوشن؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:38,428 INFO synthesis text ئەرێ هوین دکەیفخوشن؟
2026-10-13 08:59:39,729 INFO yield speech len 1.68, rtf 0.774137746720087
100%|██████████| 1/1 [00:02<00:00,  2.66s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:41,119 INFO synthesis text ئەرێ هوکارێن هونەری بووینە ئەگەرێ ڤان جورە ئقتباسان یان ئارمانجێن بازرگانی بۆ بەرهەمئینانا فلمی ل بەرچاڤ بووینە؟
2026-10-13 08:59:46,074 INFO yield speech len 7.8, rtf 0.6352401696718656
100%|██████████| 1/1 [00:06<00:00,  6.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:46,129 WARNING synthesis text ئەرێ وە گوت شێخ ئادی چینا شیخاتیێ پەیدا کریە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:47,486 INFO synthesis text ئەرێ وە گوت شێخ ئادی چینا شیخاتیێ پەیدا کریە؟
2026-10-13 08:59:50,164 INFO yield speech len 3.92, rtf 0.6832228023178724
100%|██████████| 1/1 [00:04<00:00,  4.04s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:51,556 INFO synthesis text ئەرێ یا بەرعاقلە، کو زاروک حەز ب کەت بلەز مەزن ببیت و ژ وێ ژیانا بێ گونەهـ دەرکەڤیت؟
2026-10-13 08:59:55,520 INFO yield speech len 6.0, rtf 0.6606691678365072
100%|██████████| 1/1 [00:05<00:00,  5.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:55,562 WARNING synthesis text ئەرێ یێ ل کولانا یێ هەوە ژیک ل کولانایە؟ too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 08:59:56,908 INFO synthesis text ئەرێ یێ ل کولانا یێ هەوە ژیک ل کولانایە؟
2026-10-13 08:59:59,137 INFO yield speech len 3.08, rtf 0.7235857573422518
100%|██████████| 1/1 [00:03<00:00,  3.58s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 08:59:59,167 WARNING synthesis text ئەرێ، ئەرێ، ڕیچاردی زوها  گوت. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:00,508 INFO synthesis text ئەرێ، ئەرێ، ڕیچاردی زوها  گوت.
2026-10-13 09:00:02,597 INFO yield speech len 2.88, rtf 0.7251419954829746
100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:03,996 INFO synthesis text ھەی ماشائەاللە، ئەڤ زارۆکە چەند یێ ب رەوشت و زمان شرینە، ب کەسێ مالێ ڤە نەچویە!
2026-10-13 09:00:08,193 INFO yield speech len 6.32, rtf 0.6641295137284677
100%|██████████| 1/1 [00:05<00:00,  5.55s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:08,244 WARNING synthesis text ئەرێ، ئەزبەنی، مەکسیکی گوت، یێکو ناڤێ وی کایتانو ڕویز بوو. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:09,602 INFO synthesis text ئەرێ، ئەزبەنی، مەکسیکی گوت، یێکو ناڤێ وی کایتانو ڕویز بوو.
2026-10-13 09:00:12,572 INFO yield speech len 4.44, rtf 0.6687288885717992
100%|██████████| 1/1 [00:04<00:00,  4.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:12,618 WARNING synthesis text ئەرێ، ئەم لێدانێ دخوین، ماکومبەری گوت، هێش بەرێ خو نەددا وی. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:13,974 INFO synthesis text ئەرێ، ئەم لێدانێ دخوین، ماکومبەری گوت، هێش بەرێ خو نەددا وی.
2026-10-13 09:00:16,988 INFO yield speech len 4.56, rtf 0.6609046668337103
100%|██████████| 1/1 [00:04<00:00,  4.37s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:17,038 WARNING synthesis text ئەرێ، ئەو بەری دوو حەفتییان ژ بەغدا بوری. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:18,393 INFO synthesis text ئەرێ، ئەو بەری دوو حەفتییان ژ بەغدا بوری.
2026-10-13 09:00:20,445 INFO yield speech len 2.8, rtf 0.732811348778861
100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:20,480 WARNING synthesis text ئەرێ، ئەو گەلەک جهێ باوەرییێ بوو. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:21,851 INFO synthesis text ئەرێ، ئەو گەلەک جهێ باوەرییێ بوو.
2026-10-13 09:00:23,691 INFO yield speech len 2.44, rtf 0.7537197871286361
100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:23,735 WARNING synthesis text ئەرێ، ئەوە یێکو ئەز ل دویڤ دگەرم. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:25,089 INFO synthesis text ئەرێ، ئەوە یێکو ئەز ل دویڤ دگەرم.
2026-10-13 09:00:27,086 INFO yield speech len 2.72, rtf 0.734219656271093
100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:27,130 WARNING synthesis text ئەرێ، بابێ من ژی دبێژیت ئێڤاری کو کومەل کومەل دهێن، ژ قوتابخانێ دزڤرن. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:28,480 INFO synthesis text ئەرێ، بابێ من ژی دبێژیت ئێڤاری کو کومەل کومەل دهێن، ژ قوتابخانێ دزڤرن.
2026-10-13 09:00:32,037 INFO yield speech len 5.44, rtf 0.6538685630349551
100%|██████████| 1/1 [00:04<00:00,  4.91s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:32,070 WARNING synthesis text ئەرێ، خاتون جونس ، نوکە ئێکسەر وەرە و خانم کلیپێ ببینە. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:33,415 INFO synthesis text ئەرێ، خاتون جونس ، نوکە ئێکسەر وەرە و خانم کلیپێ ببینە.
2026-10-13 09:00:36,187 INFO yield speech len 4.04, rtf 0.6861702050312911
100%|██████████| 1/1 [00:04<00:00,  4.12s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:36,228 WARNING synthesis text ئەرێ، مخابن تو ژ بەر مەرجێت شەڤا مرنا (کارمایکل) ی دێ کەڤی بەر گومانێ. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:37,576 INFO synthesis text ئەرێ، مخابن تو ژ بەر مەرجێت شەڤا مرنا (کارمایکل) ی دێ کەڤی بەر گومانێ.
2026-10-13 09:00:40,968 INFO yield speech len 5.2, rtf 0.6522632562197171
100%|██████████| 1/1 [00:04<00:00,  4.74s/it]
  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:41,030 WARNING synthesis text ئەرێ، هەر چەند کو ئەز شەرمزارم ل بابەتێ بێهنێ. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:42,390 INFO synthesis text ئەرێ، هەر چەند کو ئەز شەرمزارم ل بابەتێ بێهنێ.
2026-10-13 09:00:44,907 INFO yield speech len 3.56, rtf 0.7071232527829288
100%|██████████| 1/1 [00:03<00:00,  3.88s/it]

  hayfa: 100/101

  0%|          | 0/1 [00:00<?, ?it/s]2026-10-13 09:00:45,144 WARNING synthesis text ئەرێکرن، نیشانکرن، شیرانی، خەلاتبرین کرنە یەک. too short than prompt text You are a helpful assistant.<|endofprompt|>ڕەنگ ل وی نەما دەمێ وی دیتی کانێ چاوا وی داعشی سەرێ ھەڤالێ وی بڕی و ڤزکا خوینا سور ب سەر وارا ڤە چوو., this may lead to bad performance
2026-10-13 09:00:46,520 INFO synthesis text ئەرێکرن، نیشانکرن، شیرانی، خەلاتبرین کرنە یەک.
2026-10-13 09:00:49,430 INFO yield speech len 4.28, rtf 0.6800642080396135
100%|██████████| 1/1 [00:04<00:00,  4.29s/it]

  hayfa: 101/101

## 5 · Scorers (ECAPA, UTMOS, optional ASR)

In [9]:
from speechbrain.inference.speaker import EncoderClassifier
enc = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb",
        savedir="/workspace/tmp/ecapa", run_opts={"device": dev})
ums = torch.hub.load("tarepan/SpeechMOS:v1.2.0", "utmos22_strong", trust_repo=True).to(dev).eval()
def load16(p):
    w, s_ = torchaudio.load(p); w = w.mean(0, keepdim=True)
    return torchaudio.functional.resample(w, s_, 16000) if s_ != 16000 else w
def emb(p):
    with torch.no_grad(): e = enc.encode_batch(load16(p).to(dev)).squeeze()
    return torch.nn.functional.normalize(e, dim=0).cpu().numpy()
def utmos(p):
    with torch.no_grad(): return float(ums(load16(p).to(dev), 16000))

asr = None
if ASR_MODEL:
    from transformers import pipeline
    asr = pipeline("automatic-speech-recognition", model=ASR_MODEL, device=0 if dev == "cuda" else -1)
    def transcribe(p):
        a = {"raw": load16(p).squeeze(0).numpy(), "sampling_rate": 16000}
        return asr(a, generate_kwargs={"language": ASR_LANG})["text"] if ASR_LANG else asr(a)["text"]

2026-10-13 09:10:05,173 INFO Fetch hyperparams.yaml: Using symlink found at '/workspace/tmp/ecapa/hyperparams.yaml'
2026-10-13 09:10:05,426 INFO Fetch embedding_model.ckpt: Using symlink found at '/workspace/tmp/ecapa/embedding_model.ckpt'
2026-10-13 09:10:05,435 INFO Fetch mean_var_norm_emb.ckpt: Using symlink found at '/workspace/tmp/ecapa/mean_var_norm_emb.ckpt'
2026-10-13 09:10:05,445 INFO Fetch classifier.ckpt: Using symlink found at '/workspace/tmp/ecapa/classifier.ckpt'
2026-10-13 09:10:05,454 INFO Fetch label_encoder.txt: Using symlink found at '/workspace/tmp/ecapa/label_encoder.ckpt'
2026-10-13 09:10:05,455 INFO Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder
2026-10-13 09:10:06,543 WARNING Could not parse CUDA device string 'cuda': not enough values to unpack (expected 2, got 1). Falling back to device 0.
Using cache found in /root/.cache/torch/hub/tarepan_SpeechMOS_v1.2.0

## 6 · Score every utterance

In [10]:
rows = []
for s, ids in per_spk.items():
    pref = emb(PROMPT[s][0])
    for i, u in enumerate(ids, 1):
        sp = f"{SYNTH_DIR}/{s}/{u}.wav"
        if not os.path.exists(sp): continue
        real = test[u][0]; e = emb(sp)
        sd = sf.info(sp).duration; rd = sf.info(real).duration; tm = timing.get(f"{s}/{u}")
        r = dict(speaker=s, utt=u, text=test[u][1],
                 simo_prompt=float(np.dot(pref, e)), simo_real=float(np.dot(emb(real), e)),
                 utmos=utmos(sp), synth_sec=sd, real_sec=rd, dur_ratio=sd / rd if rd else float("nan"),
                 rtf=(tm["sec"] / tm["audio_sec"]) if tm and tm["audio_sec"] else float("nan"))
        if asr:
            hyp = transcribe(sp); ref = norm_text(digits_to_words(test[u][1])); hn = norm_text(hyp)
            rw, hw = ref.split(), hn.split()
            r.update(asr_text=hyp, wer=edit_distance(rw, hw) / max(len(rw), 1), cer=edit_distance(ref, hn) / max(len(ref), 1))
        rows.append(r)
        if i % 25 == 0 or i == len(ids): print(f"  scored {s}: {i}/{len(ids)}")

/workspace/envs/cosyvoice/lib/python3.10/site-packages/torchaudio/_backend/ffmpeg.py:88: UserWarning: torio.io._streaming_media_decoder.StreamingMediaDecoder has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being consolidated into TorchCodec. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release.
  s = torchaudio.io.StreamReader(src, format, None, buffer_size)

  scored bafreen: 25/101
  scored bafreen: 50/101
  scored bafreen: 75/101
  scored bafreen: 100/101
  scored bafreen: 101/101
  scored abdullah: 25/101
  scored abdullah: 50/101
  scored abdullah: 75/101
  scored abdullah: 100/101
  scored abdullah: 101/101
  scored hayfa: 25/101
  scored hayfa: 50/101
  scored hayfa: 75/101
  scored hayfa: 100/101
  scored hayfa: 101/101

## 7 · Results table, files, worst sentences

In [11]:
import pandas as pd
df = pd.DataFrame(rows)
df.to_csv(f"{OUT_DIR}/per_utterance.csv", index=False, encoding="utf-8-sig")
metrics = ["simo_prompt", "simo_real", "utmos", "rtf", "dur_ratio"] + (["cer", "wer"] if asr else [])
df["dur_outlier"] = ~df.dur_ratio.between(0.5, 2.0)      # likely truncated / looping
by_spk = df.groupby("speaker")[metrics + ["dur_outlier"]].agg({**{m: "mean" for m in metrics}, "dur_outlier": "sum"})
by_spk.insert(0, "n", df.groupby("speaker").size())
overall = pd.DataFrame({**{m: [df[m].mean()] for m in metrics}, "dur_outlier": [df.dur_outlier.sum()], "n": [len(df)]}, index=["ALL"])
summary = pd.concat([by_spk, overall[by_spk.columns]])
summary.to_csv(f"{OUT_DIR}/summary.csv", encoding="utf-8-sig")
json.dump(summary.to_dict("index"), open(f"{OUT_DIR}/summary.json", "w"), indent=1, ensure_ascii=False)
print("SIM-o / UTMOS: higher is better | RTF, CER, WER: lower is better | dur_ratio ~1.0 expected")
display(summary.round(3))
print("lowest SIM-o sentences (listen to these):")
display(df.nsmallest(5, "simo_real")[["speaker", "utt", "simo_real", "utmos", "dur_ratio"]])

SIM-o / UTMOS: higher is better | RTF, CER, WER: lower is better | dur_ratio ~1.0 expected

            n  simo_prompt  simo_real  utmos    rtf  dur_ratio  dur_outlier
abdullah  101        0.798      0.502  3.536  0.895      1.059            0
bafreen   101        0.699      0.606  3.766  1.285      1.008            4
hayfa     101        0.755      0.600  3.559  0.954      1.041            0
ALL       303        0.750      0.569  3.621  1.045      1.036            4

lowest SIM-o sentences (listen to these):

      speaker            utt  simo_real     utmos  dur_ratio
4     bafreen  1_44100_a9904  -0.031633  2.008604   0.072213
28    bafreen  1_44100_a9928  -0.027880  2.922091   0.050982
1     bafreen  1_44100_a9901   0.017666  2.892092   0.041678
15    bafreen  1_44100_a9915   0.113140  3.023997   0.044219
136  abdullah  2_44100_a7402   0.275168  3.817994   1.174564

In [14]:
for _, r in bad.iterrows(): os.remove(f"{SYNTH_DIR}/{r.speaker}/{r.utt}.wav")

AttributeError: 'set' object has no attribute 'iterrows'

In [15]:
fails = df[~df.dur_ratio.between(0.5, 2.0)]
display(fails[["speaker","utt","real_sec","synth_sec","dur_ratio","simo_real","utmos","text"]])

for _, r in fails.iterrows():
    os.remove(f"{SYNTH_DIR}/{r.speaker}/{r.utt}.wav")
print("deleted", len(fails), "wavs")

,speaker,utt,real_sec,synth_sec,dur_ratio,simo_real,utmos,text
1,bafreen,1_44100_a9901,2.879184,0.12,0.041678,0.017666,2.892092,بلا ئەزبەنی، جارێ دا شیڤا ژی بدەینێ.
4,bafreen,1_44100_a9904,5.539184,0.40,0.072213,-0.031633,2.008604,پشتی سێزدە سالان هێلا ئاسمانیا تورکیا سەر ژ نو...
15,bafreen,1_44100_a9915,1.809184,0.08,0.044219,0.113140,3.023997,ساندەرسێ روباری؟
28,bafreen,1_44100_a9928,1.569184,0.08,0.050982,-0.027880,2.922091,ژ بابێت مەنە.

deleted 4 wavs